### ISSUE TITLE
[BUG] harvester network controller manager failed to start

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1096]
**Describe the bug**
harvester network controller manager failed to start with the following errors:

```
harv-rmdv [~]$ kubectl -n harvester-system get po
NAME                                                    READY   STATUS             RESTARTS   AGE
harvester-fdb4d775f-hzrgr                               1/1     Running            0          103m
harvester-fdb4d775f-nr8nd                               0/1     Pending            0          103m
harvester-fdb4d775f-q8stb                               0/1     Pending            0          103m
harvester-network-controller-manager-67f7d797db-j2lqj   1/1     Running            20         103m
harvester-network-controller-manager-67f7d797db-w9z7b   0/1     CrashLoopBackOff   20         103m
harvester-network-controller-ml5f6                      1/1     Running            0          103m
harvester-webhook-6d94fd86cb-2kwwc                      0/1     Pending            0          103m
harvester-webhook-6d94fd86cb-5mmfc                      0/1     Pending            0          103m
harvester-webhook-6d94fd86cb-qpgnb                      1/1     Running            0          103m
virt-api-57fd7db5cc-bbmj8                               1/1     Running            0          102m
virt-api-57fd7db5cc-s4wn4                               1/1     Running            0          102m
virt-controller-b49dfc74-8bl9v                          1/1     Running            0          101m
virt-controller-b49dfc74-ltj8j                          1/1     Running            0          101m
virt-handler-ptv54                                      1/1     Running            0          101m
virt-operator-78697f6ff8-5r2jw                          1/1     Running            0          103m
harv-rmdv [~]$ kubectl -n harvester-system logs -f harvester-network-controller-manager-67f7d797db-w9z7b
I0817 09:47:51.387378       1 main.go:105] Starting network controller with 2 threads.
I0817 09:47:51.387495       1 main.go:108] Starting network controller with no namespace.
W0817 09:47:51.388065       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0817 09:47:51.681326       1 leaderelection.go:243] attempting to acquire leader lease kube-system/harvester-network-controllers...
I0817 09:48:38.127327       1 leaderelection.go:253] successfully acquired lease kube-system/harvester-network-controllers
time="2021-08-17T09:48:55Z" level=info msg="Do not update the existing CRD NetworkAttachmentDefinition"
time="2021-08-17T09:48:57Z" level=info msg="Do not update the existing CRD NodeNetwork"
panic: init clusternetwork faield, error: create clusternetwork failed, error: the server could not find the requested resource (post clusternetworks.meta.k8s.io)

goroutine 66 [running]:
main.run.func1(0x1ec1cc0, 0xc00020bf80)
        /go/src/github.com/harvester/harvester-network-controller/main.go:137 +0x13c
created by github.com/harvester/harvester-network-controller/vendor/github.com/rancher/wrangler/pkg/leader.run.func1
        /go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/wrangler/pkg/leader/leader.go:58 +0x46

```

**To Reproduce**
1. install the harvester using the `master-head.iso` created on 08-17
2. check the pod on the harvester-system

**Expected behavior**
the harvester network controller CRD is updated correctly with https://github.com/harvester/network-controller-harvester/commit/c68dcf51f5fd09625640a4c219aff6a1869941d5

**Support bundle**

**Environment:**
 - Harvester ISO version: master-head-08-17
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
Validation Steps:
1. install the harvester using the master-head.iso created on 08-18
2. check the harvester controller manager pod on the `harvester-system` is healthy and its log does not contain any fatal errors.

**Comment by ldevulder** [comment]
Tested with the latest `master-head` version (don't know the exact version number because of #1094).
I installed a 5 nodes cluster and I was not able to reproduce the issue:
```
hpd12s11 [~]$ kubectl get po -n harvester-system
NAME                                                    READY   STATUS      RESTARTS   AGE
harvester-fdb4d775f-b4hms                               1/1     Running     0          13m
harvester-fdb4d775f-d6cng                               1/1     Running     0          13m
harvester-fdb4d775f-sddl4                               1/1     Running     0          13m
harvester-network-controller-5h6zk                      1/1     Running     0          107s
harvester-network-controller-8bzxc                      1/1     Running     0          117s
harvester-network-controller-bjmg6                      1/1     Running     0          13m
harvester-network-controller-fd9nw                      1/1     Running     0          101s
harvester-network-controller-manager-67f7d797db-2fffv   1/1     Running     0          13m
harvester-network-controller-manager-67f7d797db-k4fwz   1/1     Running     0          13m
harvester-network-controller-rdqp4                      1/1     Running     0          48s
harvester-promote-hpd12s14-22pdj                        0/1     Completed   0          107s
harvester-promote-hpd12s16-rlnkb                        0/1     Completed   0          69s
harvester-webhook-6d94fd86cb-frrgr                      1/1     Running     0          13m
harvester-webhook-6d94fd86cb-mjks6                      1/1     Running     0          13m
harvester-webhook-6d94fd86cb-smjvh                      1/1     Running     0          13m
virt-api-57fd7db5cc-qkkrt                               1/1     Running     0          11m
virt-api-57fd7db5cc-vj4j2                               1/1     Running     0          11m
virt-controller-b49dfc74-rktbf                          1/1     Running     0          11m
virt-controller-b49dfc74-vm9c2                          1/1     Running     0          11m
virt-handler-8x789                                      1/1     Running     0          48s
virt-handler-9zfk6                                      1/1     Running     0          101s
virt-handler-gnz42                                      1/1     Running     0          107s
virt-handler-wfxfz                                      1/1     Running     0          117s
virt-handler-whlm6                                      1/1     Running     0          11m
virt-operator-78697f6ff8-56hht                          1/1     Running     0          13m
```

Logs look good:
```
hpd12s11 [~]$ kubectl -n harvester-system logs -f harvester-network-controller-manager-67f7d797db-2fffv
I0818 09:44:38.215683       1 main.go:105] Starting network controller with 2 threads.
I0818 09:44:38.215774       1 main.go:108] Starting network controller with no namespace.
W0818 09:44:38.216078       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0818 09:44:38.415943       1 leaderelection.go:243] attempting to acquire leader lease kube-system/harvester-network-controllers...
^C
hpd12s11 [~]$ kubectl -n harvester-system logs -f harvester-network-controller-manager-67f7d797db-k4fwz
I0818 09:44:38.215107       1 main.go:105] Starting network controller with 2 threads.
I0818 09:44:38.215172       1 main.go:108] Starting network controller with no namespace.
W0818 09:44:38.215414       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0818 09:44:38.289981       1 leaderelection.go:243] attempting to acquire leader lease kube-system/harvester-network-controllers...
I0818 09:44:38.621639       1 leaderelection.go:253] successfully acquired lease kube-system/harvester-network-controllers
time="2021-08-18T09:44:45Z" level=info msg="Do not update the existing CRD NodeNetwork"
time="2021-08-18T09:44:46Z" level=info msg="Do not update the existing CRD NetworkAttachmentDefinition"
time="2021-08-18T09:44:52Z" level=info msg="Starting network.harvesterhci.io/v1beta1, Kind=ClusterNetwork controller"
I0818 09:44:52.716877       1 controller.go:59] cluster network configuration vlan has been changed
time="2021-08-18T09:44:52Z" level=info msg="Starting /v1, Kind=Node controller"
time="2021-08-18T09:44:52Z" level=info msg="Starting network.harvesterhci.io/v1beta1, Kind=NodeNetwork controller"
I0818 09:44:52.722889       1 controller.go:49] new node hpd12s11 added
I0818 09:44:52.730309       1 controller.go:59] cluster network configuration vlan has been changed
I0818 09:45:00.754649       1 controller.go:49] new node hpd12s11 added
```

This issue can be closed.
