### ISSUE TITLE
[BUG] terraform provider harvester panic if set `machine_type`

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1108]
**Describe the bug**

```bash
harvester_virtualmachine.ubuntu20-dev: Creating...
╷
│ Error: Plugin did not respond
│
│   with harvester_virtualmachine.ubuntu20-dev,
│   on ubuntu.tf line 3, in resource "harvester_virtualmachine" "ubuntu20-dev":
│    3: resource "harvester_virtualmachine" "ubuntu20-dev" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-harvester_v0.1.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x198bcb3]

goroutine 46 [running]:
github.com/harvester/harvester/pkg/builder.(*VMBuilder).MachineType(...)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/github.com/harvester/harvester/pkg/builder/vm.go:102
github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine.(*Constructor).Setup.func4(0x1adb580, 0xc000287340, 0xc, 0x1adb580)
        /home/mate/dev/futuretea/terraform-provider-harvester/internal/provider/virtualmachine/resource_virtualmachine_constructor.go:57 +0x53
github.com/harvester/terraform-provider-harvester/internal/util.ResourceConstruct(0xc0002c2e80, 0x20a2618, 0xc00013b130, 0xc, 0x20a2618, 0xc00013b130, 0x0)
        /home/mate/dev/futuretea/terraform-provider-harvester/internal/util/constructor.go:102 +0x25d
github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine.resourceVirtualMachineCreate(0x20d1f08, 0xc00069c300, 0xc0002c2e80, 0x1a43920, 0xc0000ed050, 0xc000549f20, 0xaa088a, 0xc0006d0900)
        /home/mate/dev/futuretea/terraform-provider-harvester/internal/provider/virtualmachine/resource_virtualmachine.go:36 +0x13d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002988c0, 0x20d1e98, 0xc00054c040, 0xc0002c2e80, 0x1a43920, 0xc0000ed050, 0x0, 0x0, 0x0)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:330 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002988c0, 0x20d1e98, 0xc00054c040, 0xc0003381c0, 0xc0006d0900, 0x1a43920, 0xc0000ed050, 0x0, 0x0, 0x0, ...)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006c58c0, 0x20d1e98, 0xc00054c040, 0xc000296af0, 0xc00054c040, 0x1d4fcc0, 0xc000536f00)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00007ea00, 0x20d1f40, 0xc00054c040, 0xc0002cac40, 0xc00007ea00, 0xc000408ba0, 0x46d7c7)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1d4fcc0, 0xc00007ea00, 0x20d1f40, 0xc000536f60, 0xc0006c6f00, 0x0, 0x20d1f40, 0xc000536f60, 0xc0002d7b00, 0xc98)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000222700, 0x20e50d8, 0xc000103680, 0xc0005c6d00, 0xc0001b51d0, 0x2e6a6e0, 0x0, 0x0, 0x0)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/google.golang.org/grpc/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000222700, 0x20e50d8, 0xc000103680, 0xc0005c6d00, 0x0)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/google.golang.org/grpc/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00003e2d0, 0xc000222700, 0x20e50d8, 0xc000103680, 0xc0005c6d00)
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/google.golang.org/grpc/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/mate/dev/futuretea/terraform-provider-harvester/vendor/google.golang.org/grpc/server.go:869 +0x1fd

Error: The terraform-provider-harvester_v0.1.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**To Reproduce**
1. use terraform-provider-harvester to create a vm (set machine_type)
```hcl
resource "harvester_virtualmachine" "ubuntu20-dev" {
  name        = "ubuntu20-dev"
  description = "test raw image"

  tags = {
    ssh-user = "ubuntu"
  }

  cpu    = 2
  memory = "2Gi"

  start        = true
  hostname     = "ubuntu-dev"
  machine_type = "q35"

  ssh_keys = [
    "mysshkey"
  ]

  network_interface {
    name         = "nic-1"
    network_name = "harvester-public/vlan1"
  }

  network_interface {
    name         = "nic-2"
    model        = "virtio"
    type         = "bridge"
    network_name = "harvester-public/vlan2"
  }

  network_interface {
    name         = "nic-3"
    model        = "e1000"
    type         = "bridge"
    network_name = "harvester-public/vlan3"
  }

  disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image = "harvester-public/ubuntu20"
  }

  disk {
    name = "emptydisk"
    type = "disk"
    size = "20Gi"
    bus  = "virtio"
  }

  disk {
    name = "mount-disk"
    type = "disk"
    bus  = "virtio"

    existing_volume_name = "ubuntu20-dev-mount-disk"
    auto_delete          = false
  }

  cloudinit {
    user_data    = <<-EOF
      #cloud-config
      user: ubuntu
      password: root
      chpasswd:
        expire: false
      ssh_pwauth: true
      package_update: true
      packages:
        - qemu-guest-agent
      runcmd:
        - - systemctl
          - enable
          - '--now'
          - qemu-guest-agent
      ssh_authorized_keys:
        - >-
          your ssh public key
      EOF
    network_data = ""
  }
}
```
**Expected behavior**

no panic 

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
should be addressed via https://github.com/harvester/harvester/pull/1107

**Comment by yasker** [comment]
~~@slickwarren can you help to validate this?~~

Need to reassign due to Caleb is on other tasks.

**Comment by chajain** [comment]
Verified it by creating a VM using terraform and specifying the machine_type in the resource for VM.
