### ISSUE TITLE
[BUG] Rancher: Import Harvester cluster stuck at pending

### ISSUE THREAD

**Issue by Jellyfrog** [harvester/harvester#1367]
**Describe the bug**

Rancher fails to import a  harvester cluster, it just stuck at "pending"

**To Reproduce**
1. Run rancher with: `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.6.1-rc11`
2. Go to https://< rancher-ip >/dashboard/c/local/harvesterManager/harvesterhci.io.management.cluster
3. Import cluster
4. On harvester node (sorry, I had tried before):
```
curl --insecure -sfL https://10.48.11.68/v3/import/6svcf8qwbmgzzv8zn9pncxbvpnmsqqgzmnrmzl6fz8lblqpj2cx6hj_c-m-hcnqpr7w.yaml | kubectl apply -f -
clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged
clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged
namespace/cattle-system unchanged
serviceaccount/cattle unchanged
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged
secret/cattle-credentials-5f42902 created
clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged
deployment.apps/cattle-cluster-agent configured
service/cattle-cluster-agent unchanged
```
5. Nothing more happens, just stuck at "pending"

**Expected behavior**

**Support bundle**

[rancher.log.gz](https://github.com/harvester/harvester/files/7297398/rancher.log.gz)

**Environment:**
 - Harvester ISO version: master from 2021-10-06
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Additional context**

**Comment by Jellyfrog** [comment]
When doing kubectl delete and then apply on the harvester side, this happend:

```
clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver created
clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master created
namespace/cattle-system created
serviceaccount/cattle created
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding created
clusterrole.rbac.authorization.k8s.io/cattle-admin created
deployment.apps/cattle-cluster-agent created
service/cattle-cluster-agent created
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "rancher.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": service "rancher-webhook" not found

```

**Comment by Jellyfrog** [comment]
This loops on the harvester node also:

```
Oct 06 21:44:06 rancher06 systemd[1]: Started Rancher System Agent.
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]: time="2021-10-06T21:44:06Z" level=info msg="Rancher System Agent version v0.1.1-rc1 (2988707) is starting"
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]: time="2021-10-06T21:44:06Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]: time="2021-10-06T21:44:06Z" level=debug msg="Instantiated new image utility with imagesDir: /var/lib/rancher/agent/images, imageCredentialProviderConfig: /var/lib/rancher/credentialprovider/config.yaml, imageCredentialProviderBinDir: /var/lib/rancher/credentialprovider/bin, agentRegistriesFile: /etc/rancher/agent/registries.yaml"
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]: time="2021-10-06T21:44:06Z" level=info msg="Starting remote watch of plans"
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]: panic: error while connecting to Kubernetes cluster: Get "https://10.48.11.70/version": x509: certificate is valid for 10.52.0.174, 10.53.152.93, not 10.48.11.70
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]: goroutine 10 [running]:
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]: github.com/rancher/system-agent/pkg/k8splan.(*watcher).start(0xc0003eb380, 0x1757da0, 0xc000436dc0)
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:96 +0xc74
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]: created by github.com/rancher/system-agent/pkg/k8splan.Watch
Oct 06 21:44:06 rancher06 rancher-system-agent[4283]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:57 +0xbe
Oct 06 21:44:06 rancher06 systemd[1]: rancher-system-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 06 21:44:06 rancher06 systemd[1]: rancher-system-agent.service: Failed with result 'exit-code'.
```

`rancher06` = Harvester node (I had a brain-fart when I installed it)
`10.48.11.70` = VIP IP for harvester mgmt

**Comment by guangbochen** [comment]
Deleting with `kubectl` will also remove the embedded rancher which is needed of the Harvester, so instead, u should just check the error logs of the rancher agent pod of why the connection can not be established.

**Comment by Jellyfrog** [comment]
I reinstalled harvester and tried again.
I'm not sure which is the rancher agent pod:

```
# kubectl get deployments -A
NAMESPACE                   NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
cattle-fleet-local-system   fleet-agent                            1/1     1            1           75m
cattle-fleet-system         fleet-controller                       1/1     1            1           77m
cattle-fleet-system         gitjob                                 1/1     1            1           77m
cattle-system               cattle-cluster-agent                   1/1     1            1           6m51s
cattle-system               rancher                                1/1     1            1           132m
cattle-system               rancher-webhook                        1/1     1            1           77m
cattle-system               system-upgrade-controller              1/1     1            1           74m
harvester-system            harvester                              1/1     1            1           128m
harvester-system            harvester-load-balancer                1/1     1            1           128m
harvester-system            harvester-network-controller-manager   2/2     2            2           128m
harvester-system            harvester-webhook                      1/1     1            1           128m
harvester-system            virt-api                               2/2     2            2           104m
harvester-system            virt-controller                        2/2     2            2           89m
harvester-system            virt-operator                          1/1     1            1           128m
kube-system                 rke2-coredns-rke2-coredns              1/1     1            1           130m
kube-system                 rke2-coredns-rke2-coredns-autoscaler   1/1     1            1           130m
kube-system                 rke2-metrics-server                    1/1     1            1           123m
kube-system                 snapshot-controller                    2/2     2            2           128m
longhorn-system             csi-attacher                           3/3     3            3           108m
longhorn-system             csi-provisioner                        3/3     3            3           107m
longhorn-system             csi-resizer                            3/3     3            3           107m
longhorn-system             csi-snapshotter                        3/3     3            3           107m
longhorn-system             longhorn-driver-deployer               1/1     1            1           128m
longhorn-system             longhorn-ui                            1/1     1            1           128m


# kubectl get pods -A
NAMESPACE                   NAME                                                    READY   STATUS             RESTARTS   AGE
cattle-fleet-local-system   fleet-agent-7f8fb95878-lgqzj                            1/1     Running            0          75m
cattle-fleet-system         fleet-controller-86f55db865-wcxw4                       1/1     Running            0          78m
cattle-fleet-system         gitjob-5778966b7c-7srr8                                 1/1     Running            0          78m
cattle-system               cattle-cluster-agent-868989bb69-n24qk                   1/1     Running            2          7m40s
cattle-system               rancher-5448d6c5c6-vjgbr                                1/1     Running            0          132m
cattle-system               rancher-webhook-fcd8cdc88-srp5t                         1/1     Running            0          78m
cattle-system               system-upgrade-controller-679575c7b4-twcxm              1/1     Running            0          75m
default                     virt-launcher-rancher-9fvfc                             1/1     Running            0          15m
harvester-system            harvester-67fc9778fb-7llcp                              1/1     Running            3          129m
harvester-system            harvester-load-balancer-59bf75f489-7lxrp                1/1     Running            1          129m
harvester-system            harvester-network-controller-manager-77b596f58d-d2cxz   1/1     Running            7          129m
harvester-system            harvester-network-controller-manager-77b596f58d-ptd5p   1/1     Running            8          129m
harvester-system            harvester-network-controller-s8s8r                      1/1     Running            5          129m
harvester-system            harvester-node-disk-manager-5jxx6                       1/1     Running            1          129m
harvester-system            harvester-webhook-5955cd87bb-mkjd6                      1/1     Running            1          129m
harvester-system            kube-vip-bzgrj                                          1/1     Running            13         129m
harvester-system            kube-vip-cloud-provider-0                               1/1     Running            12         129m
harvester-system            virt-api-86455cdb7d-5gstr                               1/1     Running            0          98m
harvester-system            virt-api-86455cdb7d-zkr4t                               1/1     Running            0          98m
harvester-system            virt-controller-5f649999dd-6f979                        1/1     Running            0          89m
harvester-system            virt-controller-5f649999dd-ztz5g                        1/1     Running            1          89m
harvester-system            virt-handler-2bxzw                                      1/1     Running            0          89m
harvester-system            virt-operator-56c5bdc7b8-chqpw                          1/1     Running            8          129m
kube-system                 cloud-controller-manager-harvester1100                  1/1     Running            13         132m
kube-system                 etcd-harvester1100                                      1/1     Running            0          132m
kube-system                 helm-install-harvester-gf8vv                            0/1     Completed          0          132m
kube-system                 helm-install-rancher-monitoring-cph4r                   0/1     CrashLoopBackOff   29         132m
kube-system                 helm-install-rancher-monitoring-crd-lwz2f               0/1     CrashLoopBackOff   29         132m
kube-system                 helm-install-rke2-canal-65dc5                           0/1     Completed          0          132m
kube-system                 helm-install-rke2-coredns-pqtn8                         0/1     Completed          0          132m
kube-system                 helm-install-rke2-metrics-server-grs7q                  0/1     Completed          0          132m
kube-system                 helm-install-rke2-multus-x2vkd                          0/1     Completed          0          132m
kube-system                 kube-apiserver-harvester1100                            1/1     Running            0          133m
kube-system                 kube-controller-manager-harvester1100                   1/1     Running            11         133m
kube-system                 kube-multus-ds-cwdhs                                    1/1     Running            0          131m
kube-system                 kube-proxy-harvester1100                                1/1     Running            0          133m
kube-system                 kube-scheduler-harvester1100                            1/1     Running            11         133m
kube-system                 rke2-canal-wddtv                                        2/2     Running            1          130m
kube-system                 rke2-coredns-rke2-coredns-7bb4f446c-4hkvr               1/1     Running            1          130m
kube-system                 rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-chkpm   1/1     Running            2          130m
kube-system                 rke2-metrics-server-5df7d77b5b-mz8z2                    1/1     Running            2          124m
kube-system                 snapshot-controller-9f68fdd9-clkvf                      1/1     Running            7          129m
kube-system                 snapshot-controller-9f68fdd9-kghqd                      1/1     Running            6          129m
longhorn-system             backing-image-manager-c00e-0c11                         1/1     Running            0          23m
longhorn-system             csi-attacher-76dd5cb78b-jng47                           1/1     Running            2          106m
longhorn-system             csi-attacher-76dd5cb78b-k2wm5                           1/1     Running            3          106m
longhorn-system             csi-attacher-76dd5cb78b-npwrf                           1/1     Running            3          106m
longhorn-system             csi-provisioner-7bd455f64b-m5x6q                        1/1     Running            2          106m
longhorn-system             csi-provisioner-7bd455f64b-vnghp                        1/1     Running            3          106m
longhorn-system             csi-provisioner-7bd455f64b-zdxxj                        1/1     Running            3          106m
longhorn-system             csi-resizer-5f57c65487-q5j6w                            1/1     Running            3          106m
longhorn-system             csi-resizer-5f57c65487-vkr5x                            1/1     Running            2          106m
longhorn-system             csi-resizer-5f57c65487-xkzck                            1/1     Running            2          106m
longhorn-system             csi-snapshotter-749df8dfcf-cwc6w                        1/1     Running            2          106m
longhorn-system             csi-snapshotter-749df8dfcf-g5xv9                        1/1     Running            3          106m
longhorn-system             csi-snapshotter-749df8dfcf-hcbsx                        1/1     Running            2          106m
longhorn-system             engine-image-ei-d9402c3f-bkfr7                          1/1     Running            0          112m
longhorn-system             instance-manager-e-b17da3fb                             1/1     Running            0          71m
longhorn-system             instance-manager-r-5ea9b126                             1/1     Running            0          24m
longhorn-system             longhorn-csi-plugin-6gzxr                               2/2     Running            1          106m
longhorn-system             longhorn-driver-deployer-748f675966-5n9g7               1/1     Running            0          129m
longhorn-system             longhorn-manager-9dpng                                  1/1     Running            0          129m
longhorn-system             longhorn-ui-7bd675f6c-2ffds                             1/1     Running            1          129m
```

Harvester support bundle;
[supportbundle_d2879609-f1d5-4132-a390-3e22ebf58036_2021-10-07T13-35-39Z.zip](https://github.com/harvester/harvester/files/7303730/supportbundle_d2879609-f1d5-4132-a390-3e22ebf58036_2021-10-07T13-35-39Z.zip)

Rancher docker logs:
[rancher.log.gz](https://github.com/harvester/harvester/files/7303762/rancher.log.gz)

**Comment by Jellyfrog** [comment]
Around 13:30 UTC I tried to install it.

One error:
```
2021-10-07T13:30:29.853713198Z CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
2021-10-07T13:30:29.853862375Z set +v -x
2021-10-07T13:30:29.853869238Z + [[ true != \t\r\u\e ]]
2021-10-07T13:30:29.853897476Z + [[ '' == \1 ]]
2021-10-07T13:30:29.853902157Z + [[ '' == \v\2 ]]
2021-10-07T13:30:29.853908984Z + [[ -n '' ]]
2021-10-07T13:30:29.853912888Z + shopt -s nullglob
2021-10-07T13:30:29.853916225Z + helm_content_decode
2021-10-07T13:30:29.853919527Z + set -e
2021-10-07T13:30:29.853923129Z + ENC_CHART_PATH=/chart/rancher-monitoring-crd.tgz.base64
2021-10-07T13:30:29.853927128Z + CHART_PATH=/tmp/rancher-monitoring-crd.tgz
2021-10-07T13:30:29.853931783Z + [[ ! -f /chart/rancher-monitoring-crd.tgz.base64 ]]
2021-10-07T13:30:29.853938474Z + return
2021-10-07T13:30:29.853946213Z + [[ install != \d\e\l\e\t\e ]]
2021-10-07T13:30:29.853950263Z + helm_repo_init
2021-10-07T13:30:29.853966280Z + grep -q -e 'https\?://'
2021-10-07T13:30:29.854783484Z chart path is a url, skipping repo update
2021-10-07T13:30:29.854792235Z + echo 'chart path is a url, skipping repo update'
2021-10-07T13:30:29.854825086Z + helm_v3 repo remove stable
2021-10-07T13:30:29.892022350Z Error: no repositories configured
2021-10-07T13:30:29.892991499Z + true
2021-10-07T13:30:29.893003228Z + return
2021-10-07T13:30:29.893043953Z + helm_update install --namespace cattle-monitoring-system --set-string global.clusterCIDR=10.52.0.0/16 --set-string global.clusterCIDRv4=10.52.0.0/16 --set-string global.clusterCIDRv6= --set-string global.clusterDNS=10.53.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.53.0.0/16 --set-string global.systemDefaultRegistry=
2021-10-07T13:30:29.893134358Z + [[ helm_v3 == \h\e\l\m\_\v\3 ]]
2021-10-07T13:30:29.893665812Z ++ helm_v3 ls --all -f '^rancher-monitoring-crd$' --namespace cattle-monitoring-system --output json
2021-10-07T13:30:29.893694958Z ++ jq -r '"\(.[0].app_version),\(.[0].status)"'
2021-10-07T13:30:29.893803433Z ++ tr '[:upper:]' '[:lower:]'
2021-10-07T13:30:30.152328920Z + LINE=,uninstalling
2021-10-07T13:30:30.152380382Z + IFS=,
2021-10-07T13:30:30.152385572Z + read -r INSTALLED_VERSION STATUS _
2021-10-07T13:30:30.152631716Z + VALUES=
2021-10-07T13:30:30.152662853Z + [[ install = \d\e\l\e\t\e ]]
2021-10-07T13:30:30.152668287Z + [[ '' =~ ^(|null)$ ]]
2021-10-07T13:30:30.152704534Z + [[ uninstalling =~ ^(|null)$ ]]
2021-10-07T13:30:30.152740124Z + [[ uninstalling =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]
2021-10-07T13:30:30.152873574Z + [[ uninstalling == \d\e\p\l\o\y\e\d ]]
2021-10-07T13:30:30.152896787Z + [[ uninstalling =~ ^(deleted|failed|null|unknown)$ ]]
2021-10-07T13:30:30.152994777Z + helm_v3 install --namespace cattle-monitoring-system --set-string global.clusterCIDR=10.52.0.0/16 --set-string global.clusterCIDRv4=10.52.0.0/16 --set-string global.clusterCIDRv6= --set-string global.clusterDNS=10.53.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.53.0.0/16 --set-string global.systemDefaultRegistry= rancher-monitoring-crd https://localhost:9345/static/charts/rancher-monitoring-crd-100.0.0+up16.6.0.tgz
2021-10-07T13:30:30.315200459Z Error: cannot re-use a name that is still in use
```

```
2021-10-07T13:31:21.330883229Z CHART="${CHART//%\{KUBERNETES_API\}%/${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}}"
2021-10-07T13:31:21.330903395Z set +v -x
2021-10-07T13:31:21.330925752Z + [[ true != \t\r\u\e ]]
2021-10-07T13:31:21.330938785Z + [[ '' == \1 ]]
2021-10-07T13:31:21.330969802Z + [[ '' == \v\2 ]]
2021-10-07T13:31:21.330979844Z + [[ -n '' ]]
2021-10-07T13:31:21.330993745Z + shopt -s nullglob
2021-10-07T13:31:21.331014477Z + helm_content_decode
2021-10-07T13:31:21.331026485Z + set -e
2021-10-07T13:31:21.331056275Z + ENC_CHART_PATH=/chart/rancher-monitoring.tgz.base64
2021-10-07T13:31:21.331091834Z + CHART_PATH=/tmp/rancher-monitoring.tgz
2021-10-07T13:31:21.331104815Z + [[ ! -f /chart/rancher-monitoring.tgz.base64 ]]
2021-10-07T13:31:21.331108740Z + return
2021-10-07T13:31:21.331134100Z + [[ install != \d\e\l\e\t\e ]]
2021-10-07T13:31:21.331140807Z + helm_repo_init
2021-10-07T13:31:21.331149057Z + grep -q -e 'https\?://'
2021-10-07T13:31:21.331935776Z + echo 'chart path is a url, skipping repo update'
2021-10-07T13:31:21.331947056Z + helm_v3 repo remove stable
2021-10-07T13:31:21.331974957Z chart path is a url, skipping repo update
2021-10-07T13:31:21.369699519Z Error: no repositories configured
2021-10-07T13:31:21.373165795Z + true
2021-10-07T13:31:21.373563161Z + return
2021-10-07T13:31:21.373575037Z + helm_update install --namespace cattle-monitoring-system --set-string global.clusterCIDR=10.52.0.0/16 --set-string global.clusterCIDRv4=10.52.0.0/16 --set-string global.clusterCIDRv6= --set-string global.clusterDNS=10.53.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.53.0.0/16 --set-string global.systemDefaultRegistry=
2021-10-07T13:31:21.373590905Z + [[ helm_v3 == \h\e\l\m\_\v\3 ]]
2021-10-07T13:31:21.373942433Z ++ helm_v3 ls --all -f '^rancher-monitoring$' --namespace cattle-monitoring-system --output json
2021-10-07T13:31:21.373956333Z ++ jq -r '"\(.[0].app_version),\(.[0].status)"'
2021-10-07T13:31:21.374021390Z ++ tr '[:upper:]' '[:lower:]'
2021-10-07T13:31:21.700988908Z + LINE=null,null
2021-10-07T13:31:21.701025684Z + IFS=,
2021-10-07T13:31:21.701030684Z + read -r INSTALLED_VERSION STATUS _
2021-10-07T13:31:21.701290894Z + VALUES=
2021-10-07T13:31:21.701323568Z + for VALUES_FILE in /config/*.yaml
2021-10-07T13:31:21.701366401Z + VALUES=' --values /config/values-01_HelmChart.yaml'
2021-10-07T13:31:21.701372369Z + [[ install = \d\e\l\e\t\e ]]
2021-10-07T13:31:21.701376324Z + [[ null =~ ^(|null)$ ]]
2021-10-07T13:31:21.701403745Z + [[ null =~ ^(|null)$ ]]
2021-10-07T13:31:21.701489585Z + helm_v3 install --namespace cattle-monitoring-system --set-string global.clusterCIDR=10.52.0.0/16 --set-string global.clusterCIDRv4=10.52.0.0/16 --set-string global.clusterCIDRv6= --set-string global.clusterDNS=10.53.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.53.0.0/16 --set-string global.systemDefaultRegistry= rancher-monitoring https://localhost:9345/static/charts/rancher-monitoring-100.0.0+up16.6.0.tgz --values /config/values-01_HelmChart.yaml
2021-10-07T13:31:49.221340627Z Error: execution error at (rancher-monitoring/templates/validate-install-crd.yaml:18:7): Required CRDs are missing. Please install the corresponding CRD chart before installing this chart.
```

**Comment by guangbochen** [comment]
the existing helm release is not cleaned up properly, I would recommend just to re-install the cluster via the ISO if u can, thanks.

**Comment by Jellyfrog** [comment]
The new logs are from a complete reinstall of Harvester (rancher was on a vm inside it)

**Comment by Jellyfrog** [comment]
One problem also seems to be that `cattle-cluster-agent` pod can't connect to Rancher;
Rancher is installed on a VM inside Harvester, with the VLAN network.

```
INFO: Environment: CATTLE_ADDRESS=10.52.0.76 CATTLE_CA_CHECKSUM=273fccd5d43785724e9b1dc60d2c063b65c72149ef79eed1c8036f224e2cf3f0 CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.53.29.216:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.53.29.216:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.53.29.216 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.53.29.216:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.53.29.216 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.53.29.216 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-868989bb69-tjwjt CATTLE_SERVER=https://10.48.11.68 CATTLE_SERVER_VERSION=v2.6.1-rc11
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.53.0.10 options ndots:5
ERROR: https://10.48.11.68/ping is not accessible (Failed to connect to 10.48.11.68 port 443: Connection timed out)
```

It can reach internet, but not the vm running rancher (no firewalls installed):
```
cattle-cluster-agent-868989bb69-vdk5x:/var/lib/rancher # curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

cattle-cluster-agent-868989bb69-vdk5x:/var/lib/rancher # curl https://10.48.11.68 -v
*   Trying 10.48.11.68:443...
* TCP_NODELAY set

```


From Harvester node:
```
# curl https://10.48.11.68/ping -k
pong
```

**Comment by gitlawr** [comment]
The connectivity problem is the cause of the pending status.

It looks like the Rancher IP and the VIP are of the same cidr. Is the vlan network using the same vlan id as the management network?

**Comment by Jellyfrog** [comment]
Yes! And this seems to be the problem. I should have kept the mgmt interface and added a second for external communications
