### ISSUE TITLE
[Bug]Cannot install 'panic: invalid dimensions'

### ISSUE THREAD

**Issue by NosIreland** [harvester/harvester#1792]
**Describe the bug**
Cannot install Harvester 1.0.0. Getting 'panic: invalid dimensions' after entering hostname and hitting enter
![image](https://user-images.githubusercontent.com/19308746/148647191-6b4d038b-2638-4c3a-9c12-23d3bcefb064.png)

**To Reproduce**
1. Boot from ISO
2. Start install
3. 'Choose installation mode', Create new cluster or join existing
4. Select disk(MBR setting does not make difference)
5. Enter hostname and press enter or without entering hostname press arrow down key. 
6. A quick message appears and disappears and it is back to 'Choose installation mode'

**Expected behavior**
After entering hostname I should be able to select management NIC

**Support bundle**

Cannot get any logs as it does not start install

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Additional context**

**Comment by bk201** [comment]
The display area might be too small. Does the console resolution look normal?
These steps might help:
- Add `nomodeset` kernel parameter: https://docs.harvesterhci.io/v1.0/install/usb-install/#graphics-issue
- Manually specify the VGA mode in the kernel parameters. `vga=791` will be a good start, for all modes please check: https://en.wikipedia.org/wiki/VESA_BIOS_Extensions#Linux_video_mode_numbers

**Comment by NosIreland** [comment]
Thanks. It looks like it does not like nvidia cards. 
Got it installed.

**Comment by datallboy** [comment]
I also have this issue. Attempting to install on a Dell Precision T7600. Tried with a NVIDIA Quadro 4000. 

Display appears to be 1920x1080.

**Comment by tlehman** [comment]
@datallboy I ran into this issue on a Dell Precision T7500, did [this suggestion](https://github.com/harvester/harvester/issues/1792#issuecomment-1008531918) help?

**Comment by tlehman** [comment]
on a Dell Precision T7500, I just tried adding `nomodeset vga=791` and it didn't panic because of invalid dimensions

**Comment by matttrach** [comment]
I have this problem installing on Harvester v1.1.0, what is interesting is that Harvester v1.0.3 works just fine. I am using a MinisForum EliteMini HX90 which has an AMD Ryzen 9 with integrated Radeon graphics.

**Comment by db-at-work** [comment]
This is still an issue when working with serial console (SOL) alone:

```
2023/05/31 14:16:13 invalid dimensions
panic: invalid dimensions


goroutine 1 [running]:
log.Panicln({0xc00041ff60?, 0x0?, 0x0?})
	/usr/local/go/src/log/log.go:399 +0x65
main.main()
	/go/src/github.com/harvester/harvester-installer/main.go:11 +0x46
```

and I have nomodeset in the args for the command line:

```
rancher:~ # cat /proc/cmdline
kernel.xz initrd=rootfs.xz root=live:http://.../install/suse/harvester/1.1.2/iso/rootfs.squashfs nomodeset rd.live.image rd.cos.disable rd.noverifyssl net.ifnames=1 ip=dhcp BOOTIF=01-1c-34-da-7f-b5-3a console=ttyS1,115200n8 harvester.install.automatic=false
```

**Comment by bk201** [comment]
@db-at-work Please see if https://github.com/harvester/harvester/issues/2708#issuecomment-1244965316 help. The serial console default dimension is too slow.

**Comment by emilianolangella** [comment]
I got the same issue trying to install Harvester v1.2.1 on DELL Precision 5820.
`nomodeset vga=791` fixed the issue.
