### ISSUE TITLE
[BUG] Upgrade: VMs fail to live-migrate to other hosts in some cases

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2029]
**Describe the bug**

The destination pod of a live-migrating VM continues erroring. The migration can never succeed.

**To Reproduce**
1. Create a v1.0.0 cluster.
2. Upgrade to a custom ISO.

I saw the upgrade-repo VM can't be live-migrated:
<img width="1871" alt="Screen Shot 2022-03-18 at 12 59 02 AM" src="https://user-images.githubusercontent.com/1691518/158855767-7e1019ab-c5cc-40bb-86fe-e6d1be159595.png">

The failure happens on the second migration of VM, the first migration succeeds.
- First migration (OK):
  - source pod image: `registry.suse.com/suse/sles/15.3/virt-launcher:0.45.0-8.4.3`
  - destination pod image: `registry.suse.com/harvester-beta/virt-launcher:0.49.0-2`
- Second migration and rest (Failure):
  - source pod image:`registry.suse.com/harvester-beta/virt-launcher:0.49.0-2`
  - destination pod image: `registry.suse.com/harvester-beta/virt-launcher:0.49.0-2` 

Destination pod fails with:
```
{"component":"virt-launcher","kind":"","level":"info","msg":"Prepared migration target pod","name":"upgrade-repo-hvst-upgrade-pxs8j","namespace":"harvester-system","pos":"server.go:171","timestamp":"2022-03-17T16:44:16.138343Z","uid":"5be1bfa7-df6a-4ef2-be38-c6b8e7d91857"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Signaled target pod virt-launcher-upgrade-repo-hvst-upgrade-pxs8j-fkmcj to cleanup","name":"upgrade-repo-hvst-upgrade-pxs8j","namespace":"harvester-system","pos":"server.go:151","timestamp":"2022-03-17T16:44:16.941232Z","uid":"5be1bfa7-df6a-4ef2-be38-c6b8e7d91857"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Signaled target pod virt-launcher-upgrade-repo-hvst-upgrade-pxs8j-fkmcj to cleanup","name":"upgrade-repo-hvst-upgrade-pxs8j","namespace":"harvester-system","pos":"server.go:151","timestamp":"2022-03-17T16:44:16.969113Z","uid":"5be1bfa7-df6a-4ef2-be38-c6b8e7d91857"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Signaled target pod virt-launcher-upgrade-repo-hvst-upgrade-pxs8j-fkmcj to cleanup","name":"upgrade-repo-hvst-upgrade-pxs8j","namespace":"harvester-system","pos":"server.go:151","timestamp":"2022-03-17T16:44:17.008409Z","uid":"5be1bfa7-df6a-4ef2-be38-c6b8e7d91857"}
panic: received early exit signal

goroutine 1 [running]:
main.waitForDomainUUID(0x4a45e1b600, 0xc00047f620, 0xc0005a0000, 0x55d89c9d8498, 0xc001a98370, 0xc00047f620)
	/home/abuild/rpmbuild/BUILD/kubevirt-0.49.0/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:267 +0x52c
main.main()
	/home/abuild/rpmbuild/BUILD/kubevirt-0.49.0/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:499 +0x1165
{"component":"virt-launcher","level":"info","msg":"Reaped pid 16 with status 512","pos":"virt-launcher.go:549","timestamp":"2022-03-17T16:44:17.840689Z"}
{"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher.go:567","timestamp":"2022-03-17T16:44:17.840791Z"}
{"component":"virt-launcher","level":"error","msg":"error when checking for istio-proxy presence","pos":"virt-launcher.go:657","reason":"Get \"http://localhost:15021/healthz/ready\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","timestamp":"2022-03-17T16:44:19.842379Z"}
```
[virt-launcher-upgrade-repo-hvst-upgrade-pxs8j-fkmcj.log](https://github.com/harvester/harvester/files/8288406/virt-launcher-upgrade-repo-hvst-upgrade-pxs8j-fkmcj.log)

**Expected behavior**

VMs should be live-migrated.

**Support bundle**

[supportbundle_a968c64f-604a-4bce-9ed1-d2bee6fe58fc_2022-03-17T17-04-55Z.zip](https://github.com/harvester/harvester/files/8288398/supportbundle_a968c64f-604a-4bce-9ed1-d2bee6fe58fc_2022-03-17T17-04-55Z.zip)

**Environment:**
 - Harvester ISO version: Custom build because there are some ongoing dependencies under development.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
Didn't see this when upgrading v1.0.1 to master builds so far.
Probably because we don't have too many changes yet (e.g. no KubeVirt, Rancher, RKE2, and Longhorn changes)

**Comment by bk201** [comment]
Didn't see this issue recently. Re-open if needed.
