### ISSUE TITLE
create default admin cause cannot add indexers to running index

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#205]
cannot add indexers to running index of the default admin
```
time="2020-11-02T02:52:31Z" level=info msg="Listening on :8443"
time="2020-11-02T02:52:32Z" level=info msg="Starting harvester.cattle.io/v1alpha1, Kind=VirtualMachineImage controller"
time="2020-11-02T02:52:32Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2020-11-02T02:52:32Z" level=info msg="Active TLS secret serving-cert (ver=1209280) (count 6): map[listener.cattle.io/cn-10.42.0.155:10.42.0.155 listener.cattle.io/cn-10.42.0.95:10.42.0.95 listener.cattle.io/cn-10.42.3.13:10.42.3.13 listener.cattle.io/cn-10.42.3.9:10.42.3.9 listener.cattle.io/cn-10.42.4.11:10.42.4.11 listener.cattle.io/cn-172.16.0.63:172.16.0.63 listener.cattle.io/hash:b9226b4a0f99901e63c93d7eb6ea5b7067e5460e32552bdccd53945329c169fa]"
I1102 02:53:14.056000       7 leaderelection.go:252] successfully acquired lease kube-system/harvester-controllers
time="2020-11-02T02:53:14Z" level=error msg="error syncing 'user-gdj99': handler user-rbac-controller: Index with name auth.harvester.cattle.io/crb-by-role-and-subject does not exist, requeuing"
time="2020-11-02T02:53:14Z" level=error msg="error syncing 'user-gdj99': handler user-rbac-controller: Index with name auth.harvester.cattle.io/crb-by-role-and-subject does not exist, requeuing"
time="2020-11-02T02:53:14Z" level=info msg="Default admin already created, skip create admin step"
panic: cannot add indexers to running index

goroutine 2457 [running]:
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/rancher/harvester/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1.(*clusterRoleBindingCache).AddIndexer(0xc002bae1b0, 0x1af2d7a, 0x30, 0x1b7cc18)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/wrangler-api/pkg/generated/controllers/rbac/v1/clusterrolebinding.go:239 +0x11d
github.com/rancher/harvester/pkg/indexeres.RegisterManagementIndexers(0xc000314380)
	/go/src/github.com/rancher/harvester/pkg/indexeres/indexer.go:22 +0xa4
github.com/rancher/harvester/pkg/controller/master.register(0x1d688a0, 0xc0010bca80, 0xc000134000, 0xc000314380, 0x0, 0x0)
	/go/src/github.com/rancher/harvester/pkg/controller/master/controller.go:39 +0xe6
github.com/rancher/harvester/pkg/controller/master.Setup.func1(0x1d688a0, 0xc0010bca80)
	/go/src/github.com/rancher/harvester/pkg/controller/master/setup.go:14 +0x54
created by github.com/rancher/harvester/vendor/github.com/rancher/wrangler/pkg/leader.run.func1
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/wrangler/pkg/leader/leader.go:58 +0x46
```

**Comment by aiwantaozi** [comment]
Can't reproduce now, will follow up if there is any update

**Comment by futuretea** [comment]
reproduce by following these steps：
1. delete configmap and users
```bash
kubectl -n harvester-system delete cm admincreated
kubectl delete users.harvester.cattle.io $(kubectl get users.harvester.cattle.io --no-headers | grep admin | awk '{print $1}')
```
2. restart harvester

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/pull/238

**Comment by guangbochen** [comment]
this issue still exists in the `harvester-v0.1.0-rc2`
![failed](https://user-images.githubusercontent.com/4569037/101916071-68740580-3c01-11eb-9717-b02cb2f40ec9.png)

**Comment by gitlawr** [comment]
Validated In version master 12/16
Following the reproduce steps mentioned in https://github.com/rancher/harvester/issues/205#issuecomment-725794457 and  https://github.com/rancher/harvester/pull/340#issue-539271987 , I don't see the error logs or harvester pod crashing.
