### ISSUE TITLE
[BUG] 3-node cluster upgrading ended with 2-node cluster and one defect node

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2275]
**Describe the bug**

// three nodes in the original cluster, upgrade from v1.0.0 -> v1.0.1
```
donna   Ready                      control-plane,etcd,master   132d   v1.21.11+rke2r1   192.168.200.142   <none>        Harvester v1.0.1   5.3.18-150300.59.60-default   containerd://1.4.13-k3s1
mike    Ready,SchedulingDisabled   control-plane,etcd,master   132d   v1.21.11+rke2r1   192.168.200.140   <none>        Harvester v1.0.1   5.3.18-150300.59.60-default   containerd://1.4.13-k3s1
```

// after upgrade, this node is lost
`harvey                                                                                  192.168.200.141`

// try to re-add "harvey" with new name "louis", still fail
`louis`

// log of harvey, when it tried to re-join the cluster

```
May 10 08:13:48 harvey rke2[15992]: panic: removed all voters
May 10 08:13:48 harvey rke2[15992]: goroutine 358 [running]:
May 10 08:13:48 harvey rke2[15992]: go.etcd.io/etcd/raft.(*raft).applyConfChange(0xc000ea0280, 0x0, 0xc004259b90, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
May 10 08:13:48 harvey rke2[15992]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20220113195313-6c2233a709e8/raft/raft.go:1514 +0x225
May 10 08:13:48 harvey rke2[15992]: go.etcd.io/etcd/raft.(*node).run(0xc00176c360)
May 10 08:13:48 harvey rke2[15992]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20220113195313-6c2233a709e8/raft/node.go:356 +0x845
May 10 08:13:48 harvey rke2[15992]: created by go.etcd.io/etcd/raft.RestartNode
May 10 08:13:48 harvey rke2[15992]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20220113195313-6c2233a709e8/raft/node.go:240 +0x330
May 10 08:13:48 harvey systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 10 08:13:48 harvey systemd[1]: rke2-server.service: Failed with result 'exit-code'.
May 10 08:13:48 harvey systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
May 10 08:13:54 harvey systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 146.
May 10 08:13:54 harvey systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
May 10 08:13:54 harvey systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
```

(from @janeczku)

**To Reproduce**
1. Upgrade a running v1.0.0 3-node cluster to v1.0.1
2. 2-node are susccessfully upgraded, but another NODE is defect

**Expected behavior**

stable upgrade

**Support bundle**

https://gist.github.com/janeczku/7d42329f40154776c4f2b108ab8db1aa 
[sb_e040_20220510.zip](https://github.com/harvester/harvester/files/8685016/sb_e040_20220510.zip)

**Environment:**
 - Harvester ISO version:  v1.0.0 -> v1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

the panic stack is similar to :
https://github.com/rancher/rke2/issues/2829

@dweomer @bk201 @guangbochen @brandond

**Comment by w13915984028** [comment]
duplicated with #2258
