### ISSUE TITLE
[BUG] rke2-server.service: Failed with result 'exit-code' & rancher-system-agent.service: Failed with 'exit-code'

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2606]
**Describe the bug**
Harvester node never becomes "ready" since rke-server.service never actually successfully runs after boot.

**To Reproduce**
- not entirely sure... the only thing changed on the node was there was a point I had physically installed a new NIC on the node, but then quickly realized my hardware switch doesn't support a 10GB backplane, only 1GB, so after powering it on and being inside of iDRAC, I just power cycled it back off, no big deal there - removed the NIC card...since it doesn't help my use-case to run 1GB capped SFP+ connection.  The node was working just fine at the end of last week.

**Expected behavior**
rke2-server.service & rancher-system-agent.service doesn't fail at boot.  `90-harvester-vip.yaml` for `/etc/rancher/rke2/config.yaml.d/` get's built?

**Environment**
 - Harvester ISO version: v1.0.3-rc-1
 - Underlying Infrastructure):
Dell PowerEdge R720, 2 x Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (total of 20cores)
64GB DDR3 ECC RAM, 1TB Samsung SSD 

**Additional context**
```
dell-poweredge-harvester-r720-v103-rc1:/home/rancher # systemctl status rke2-server.service 
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
     Loaded: loaded (/usr/local/lib/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/rke2-server.service.d
             └─override.conf
     Active: activating (auto-restart) (Result: exit-code) since Mon 2022-08-01 16:19:17 UTC; 111ms ago
       Docs: https://github.com/rancher/rke2#readme
    Process: 19039 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 19047 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 19048 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 19049 ExecStartPre=/usr/sbin/harv-update-rke2-server-url server (code=exited, status=0/SUCCESS)
    Process: 19051 ExecStart=/usr/local/bin/rke2 server (code=exited, status=2)
    Process: 19103 ExecStopPost=/bin/sh -c systemd-cgls /system.slice/rke2-server.service | grep -Eo '[0-9]+ (containerd|kubelet)' | awk '{print $1}' | xargs -r kill (code=exited, status=0/SUCCESS)
   Main PID: 19051 (code=exited, status=2)
```

```
░ Subject: A start job for unit rke2-server.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit rke2-server.service has finished with a failure.
░░ 
░░ The job identifier is 37214 and the job result is failed.
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
░░ Subject: A stop job for unit rke2-server.service has finished
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A stop job for unit rke2-server.service has finished.
░░ 
░░ The job identifier is 37341 and the job result is done.
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
░░ Subject: A start job for unit rke2-server.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit rke2-server.service has begun execution.
░░ 
░░ The job identifier is 37341.
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 sh[19400]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 sh[19402]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19405]: + HARVESTER_CONFIG_FILE=/oem/harvester.config
░░ 
░░ The job identifier is 37341.
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 sh[19400]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 sh[19402]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19405]: + HARVESTER_CONFIG_FILE=/oem/harvester.config
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19405]: + RKE2_VIP_CONFIG_FILE=/etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19405]: + case $1 in
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19405]: + rm -f /etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: time="2022-08-01T16:19:43Z" level=warning msg="not running in CIS mode"
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: time="2022-08-01T16:19:43Z" level=info msg="Starting rke2 v1.22.12-rc3+rke2r1 (1d6b8ed2640006b1aab99db0841e8ac8ad70bdaf)"
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: time="2022-08-01T16:19:43Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Aug 01 16:19:43 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: time="2022-08-01T16:19:43Z" level=info msg="Starting temporary etcd to reconcile with datastore"
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: {"level":"info","ts":"2022-08-01T16:19:44.218Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":[>
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: {"level":"info","ts":"2022-08-01T16:19:44.218Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-url>
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: {"level":"info","ts":"2022-08-01T16:19:44.218Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4",>
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: panic: freepages: failed to get all reachable pages (page 8314034286246389614: out of bounds: 12899)
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: goroutine 356 [running]:
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: go.etcd.io/bbolt.(*DB).freepages.func2(0xc0020b0840)
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0xe9
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]: created by go.etcd.io/bbolt.(*DB).freepages
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 rke2[19407]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1cd
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit rke2-server.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 2.
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit rke2-server.service has entered the 'failed' state with result 'exit-code'.
Aug 01 16:19:44 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
░░ Subject: A start job for unit rke2-server.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit rke2-server.service has finished with a failure.
░░ 
░░ The job identifier is 37341 and the job result is failed.
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 246.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ Automatic restarting of the unit rke2-server.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
░░ Subject: A stop job for unit rke2-server.service has finished
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A stop job for unit rke2-server.service has finished.
░░ 
░░ The job identifier is 37468 and the job result is done.
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
░░ Subject: A start job for unit rke2-server.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit rke2-server.service has begun execution.
░░ 
░░ The job identifier is 37468.
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 sh[19500]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 sh[19506]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19510]: + HARVESTER_CONFIG_FILE=/oem/harvester.config
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19510]: + RKE2_VIP_CONFIG_FILE=/etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19510]: + case $1 in
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[19510]: + rm -f /etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: time="2022-08-01T16:19:49Z" level=warning msg="not running in CIS mode"
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: time="2022-08-01T16:19:49Z" level=info msg="Starting rke2 v1.22.12-rc3+rke2r1 (1d6b8ed2640006b1aab99db0841e8ac8ad70bdaf)"
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: time="2022-08-01T16:19:49Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Aug 01 16:19:49 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: time="2022-08-01T16:19:49Z" level=info msg="Starting temporary etcd to reconcile with datastore"
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: {"level":"info","ts":"2022-08-01T16:19:50.420Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":[>
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: {"level":"info","ts":"2022-08-01T16:19:50.420Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-url>
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: {"level":"info","ts":"2022-08-01T16:19:50.420Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4",>
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: panic: freepages: failed to get all reachable pages (page 8314034286246389614: out of bounds: 12899)
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: goroutine 145 [running]:
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: go.etcd.io/bbolt.(*DB).freepages.func2(0xc002126e40)
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0xe9
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]: created by go.etcd.io/bbolt.(*DB).freepages
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 rke2[19512]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1cd
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit rke2-server.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 2.
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit rke2-server.service has entered the 'failed' state with result 'exit-code'.
Aug 01 16:19:50 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
░░ Subject: A start job for unit rke2-server.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit rke2-server.service has finished with a failure.
░░ 
░░ The job identifier is 37468 and the job result is failed.
```

```
Aug 01 06:31:51 dell-poweredge-harvester-r720-v103-rc1 rancher-system-agent[2554]: panic: error while connecting to Kubernetes cluster: Get "https://10.53.162.160/version": dial tcp 10.53.162.160:443:>
Aug 01 06:31:51 dell-poweredge-harvester-r720-v103-rc1 rancher-system-agent[2554]: goroutine 62 [running]:
Aug 01 06:31:51 dell-poweredge-harvester-r720-v103-rc1 rancher-system-agent[2554]: github.com/rancher/system-agent/pkg/k8splan.(*watcher).start(0xc000440100, 0x17de640, 0xc000475040)
Aug 01 06:31:51 dell-poweredge-harvester-r720-v103-rc1 rancher-system-agent[2554]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:97 +0xcb4
Aug 01 06:31:51 dell-poweredge-harvester-r720-v103-rc1 rancher-system-agent[2554]: created by github.com/rancher/system-agent/pkg/k8splan.Watch
Aug 01 06:31:51 dell-poweredge-harvester-r720-v103-rc1 rancher-system-agent[2554]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:58 +0xbe
Aug 01 06:31:51 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rancher-system-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 01 06:31:51 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rancher-system-agent.service: Failed with result 'exit-code'.
```

Seems to just be stuck in a boot loop on the systemctl service 480+ retries since boot:
```
Aug 01 16:43:11 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Aug 01 16:43:11 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 481.
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 sh[36314]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 sh[36319]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[36325]: + HARVESTER_CONFIG_FILE=/oem/harvester.config
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[36325]: + RKE2_VIP_CONFIG_FILE=/etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[36325]: + case $1 in
Aug 01 16:43:16 dell-poweredge-harvester-r720-v103-rc1 harv-update-rke2-server-url[36325]: + rm -f /etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: time="2022-08-01T16:43:17Z" level=warning msg="not running in CIS mode"
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: time="2022-08-01T16:43:17Z" level=info msg="Starting rke2 v1.22.12-rc3+rke2r1 (1d6b8ed2640006b1aab99db0841e8ac8ad70bdaf)"
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: time="2022-08-01T16:43:17Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: time="2022-08-01T16:43:17Z" level=info msg="Starting temporary etcd to reconcile with datastore"
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: {"level":"info","ts":"2022-08-01T16:43:17.823Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":[>
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: {"level":"info","ts":"2022-08-01T16:43:17.824Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-url>
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: {"level":"info","ts":"2022-08-01T16:43:17.824Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4",>
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: panic: freepages: failed to get all reachable pages (page 8314034286246389614: out of bounds: 12899)
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: goroutine 358 [running]:
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: go.etcd.io/bbolt.(*DB).freepages.func2(0xc002148240)
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0xe9
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]: created by go.etcd.io/bbolt.(*DB).freepages
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 rke2[36327]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1cd
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Aug 01 16:43:17 dell-poweredge-harvester-r720-v103-rc1 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
```

No configuration files have been modified since install of v1.0.3-rc1:
```
dell-poweredge-harvester-r720-v103-rc1:/home/rancher # ls -l /oem/
total 90
-rw-rw-rw- 1 root root 72977 Jul 27 23:07 99_custom.yaml
-rw------- 1 root root  2832 Jul 27 23:07 harvester.config
drwxr-xr-x 2 root root  1024 Jul 27 23:11 install
drwx------ 2 root root 12288 Jul 27 23:06 lost+found
-rw------- 1 root root  1356 Jul 27 23:07 part-layout.config
```

Looks like `90-harvester-vip.yaml` isn't being built:
```
dell-poweredge-harvester-r720-v103-rc1:/home/rancher # ls -alh /etc/rancher/rke2/config.yaml.d/
total 24K
drw------- 2 root root 4.0K Jul 27 23:24 .
drwxr-xr-x 3 root root 4.0K Jul 27 23:11 ..
-rw------- 1 root root   56 Jul 27 23:21 40-rancherd.yaml
-rw------- 1 root root  720 Jul 27 23:24 50-rancher.yaml
-rw------- 1 root root    1 Aug  1 15:54 90-harvester-agent.yaml
-rw------- 1 root root  123 Aug  1 15:54 90-harvester-server.yaml
```

Here is the `install.networks.harvester-mgmt` & `vip` section of the `harvester.config` that was created when walking through the guided install steps:
```
install:
  automatic: false
  mode: create
  networks:
    harvester-mgmt:
      interfaces:
      - name: eno1
        hwaddr: ""
      method: dhcp
      ip: ""
      subnetmask: ""
      gateway: ""
      defaultroute: true
      bondoptions:
        miimon: "100"
        mode: balance-tlb
      mtu: 0
  vip: 192.168.1.248
  viphwaddr: 46:23:eb:0f:e9:e1
  vipmode: dhcp
```

**Comment by irishgordo** [comment]
I'm willing to go ahead and close this, as this could be more related to hardware & a power interruption that it experienced recently. :smile:

**Comment by irishgordo** [comment]
Closing because in the meantime I need the hardware - I suspect that etcd db got corrupted due to some unexpected power issue
