### ISSUE TITLE
[BUG] harvester pod panic but console still ready

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#2778]
**Describe the bug**

server version master-032742f0-head
harvester pod panic
```
time="2022-09-19T09:58:32Z" level=info msg="Admission webhooks are ready"
I0919 09:58:32.962857       7 leaderelection.go:248] attempting to acquire leader lease kube-system/harvester-controllers...
I0919 09:58:32.975497       7 leaderelection.go:258] successfully acquired lease kube-system/harvester-controllers
panic: cannot add indexers to running index

goroutine 1 [running]:
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.Must(...)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/harvester/harvester/pkg/generated/controllers/harvesterhci.io/v1beta1.(*virtualMachineBackupCache).AddIndexer(0xc0031afec0, {0x2504c99, 0x29}, 0x25dd1f8)
        /go/src/github.com/harvester/harvester/pkg/generated/controllers/harvesterhci.io/v1beta1/virtualmachinebackup.go:239 +0xe5
github.com/harvester/harvester/pkg/indexeres.RegisterAPIIndexers(0xc000984900?)
        /go/src/github.com/harvester/harvester/pkg/indexeres/indexer.go:47 +0x62
github.com/harvester/harvester/pkg/api.Setup({0x28b4cb8?, 0xc000984900?}, 0x1c6e345?, 0xc0006ad960?, {{0xc00005206a, 0x10}, 0xa, 0x0, 0x20fb, 0x1, ...})
        /go/src/github.com/harvester/harvester/pkg/api/register.go:32 +0x76
github.com/harvester/harvester/pkg/server.(*HarvesterServer).start(0xc000adee60, {{0xc00005206a, 0x10}, 0xa, 0x0, 0x20fb, 0x1, {0x0, 0x0}, 0x1})
        /go/src/github.com/harvester/harvester/pkg/server/types.go:252 +0xce
github.com/harvester/harvester/pkg/server.(*HarvesterServer).generateSteveServer(0xc000adee60, {{0xc00005206a, 0x10}, 0xa, 0x0, 0x20fb, 0x1, {0x0, 0x0}, 0x1})
        /go/src/github.com/harvester/harvester/pkg/server/types.go:247 +0x665
github.com/harvester/harvester/pkg/server.New({0x28b4c10?, 0xc0006a34c0}, {0x28b71e8, 0xc0007182d0}, {{0xc00005206a, 0x10}, 0xa, 0x0, 0x20fb, 0x1, ...})
        /go/src/github.com/harvester/harvester/pkg/server/types.go:121 +0x2d3
main.run(0xc0006a29c0, {{0xc00005206a, 0x10}, 0xa, 0x0, 0x20fb, 0x1, {0x0, 0x0}, 0x1})
        /go/src/github.com/harvester/harvester/main.go:90 +0x145
main.main.func1(0xc0006a29c0?)
        /go/src/github.com/harvester/harvester/main.go:76 +0x48
github.com/harvester/harvester/pkg/cmd.NewApp.func1(0xc0006f46e0?)
        /go/src/github.com/harvester/harvester/pkg/cmd/app.go:70 +0x44
github.com/harvester/harvester/vendor/github.com/urfave/cli.HandleAction({0x1fd65e0?, 0xc0006922a0?}, 0xc0003076c0?)
        /go/src/github.com/harvester/harvester/vendor/github.com/urfave/cli/app.go:523 +0xa8
github.com/harvester/harvester/vendor/github.com/urfave/cli.(*App).Run(0xc0003076c0, {0xc00004c220, 0x1, 0x1})
        /go/src/github.com/harvester/harvester/vendor/github.com/urfave/cli/app.go:285 +0x818
github.com/harvester/harvester/pkg/cmd.(*App).Run(0x24d33ec?)
        /go/src/github.com/harvester/harvester/pkg/cmd/app.go:109 +0x31
main.main()
        /go/src/github.com/harvester/harvester/main.go:78 +0x413
```

![image](https://user-images.githubusercontent.com/15064560/190998730-e2d75aca-7e5e-491c-a48d-aa2e210b0ab8.png)

**To Reproduce**
this is a race condition issue
Keep watching for Harvester service availability when using master-head iso

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  master-032742f0-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-af5215bb-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes via ISO install
2. Follow **Test Plan** in https://github.com/harvester/harvester-installer/pull/339#issue-1378092118
