### ISSUE TITLE
[BUG] Harvester network webhook consumes more than 200m CPU resource

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#2941]
**Describe the bug**

harvester-network-webhook always uses up to 200m CPU(limit resource) during bootstrap. If we kill the pod once, it will become normal.

**To Reproduce**
1.  Setup a new Harvester and you'll find that.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by w13915984028** [comment]
I tried to get the stacktrace when it happens:

The bug is caused by:

```
2022-10-19T19:01:46.41219786Z stderr F goroutine 1396 [runnable]:
2022-10-19T19:01:46.412199343Z stderr F runtime.Gosched(...)
2022-10-19T19:01:46.412200936Z stderr F 	/usr/local/go/src/runtime/proc.go:317
2022-10-19T19:01:46.412205274Z stderr F github.com/harvester/harvester-network-controller/vendor/github.com/rancher/dynamiclistener.(*listener).WrapExpiration.func1()
2022-10-19T19:01:46.412206857Z stderr F 	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/dynamiclistener/listener.go:168 +0x59
2022-10-19T19:01:46.41220857Z stderr F created by github.com/harvester/harvester-network-controller/vendor/github.com/rancher/dynamiclistener.(*listener).WrapExpiration
2022-10-19T19:01:46.412210093Z stderr F 	/go/src/github.com/harvester/harvester-network-controller/vendor/github.com/rancher/dynamiclistener/listener.go:165 +0xb8
2022-10-19T19:01:46.412211476Z stderr F 

```

Related issues
https://github.com/harvester/harvester/issues/2558
https://github.com/rancher/dynamiclistener/issues/63

Booked in:
https://github.com/w13915984028/harvester-develop-summary/blob/main/harvester-pod-100-cpu-usage-issue-2558.md

**Comment by w13915984028** [comment]
need to bump

`	github.com/rancher/dynamiclistener v0.3.3 // indirect`

to

https://github.com/rancher/dynamiclistener/releases/tag/v0.3.4

cc @yaocw2020 @guangbochen @bk201

**Comment by irishgordo** [comment]
@chrisho thanks for your work on this!
Validating on:
harvester-master-head-402df54b
This looks good.
As a small performance test I did:
```bash
rancher@harvester-master-head-vm-10-24:~> for i in {1..100}; do echo "on $i iteration"; kubectl top pod harvester-network-webhook-b5b67774b-zstfq --namespace=harvester-system; sleep 5; done
on 1 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 2 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 3 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 4 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 5 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 6 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 7 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 8 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 9 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 10 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 11 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 12 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 13 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 14 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 15 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 16 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 17 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 18 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 19 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 20 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 21 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 22 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 23 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 24 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 25 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 26 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 27 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 28 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 29 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 30 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 31 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 32 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 33 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 34 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 35 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   20m          83Mi            
on 36 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 37 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 38 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   19m          83Mi            
on 39 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 40 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 41 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   18m          83Mi            
on 42 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   3m           88Mi            
on 43 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   3m           88Mi            
on 44 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   3m           88Mi            
on 45 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 46 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 47 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 48 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 49 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 50 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 51 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 52 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 53 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 54 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 55 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 56 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 57 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 58 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 59 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 60 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 61 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 62 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 63 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 64 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 65 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 66 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 67 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 68 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 69 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 70 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 71 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 72 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 73 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 74 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 75 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 76 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 77 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 78 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 79 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 80 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 81 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 82 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 83 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 84 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 85 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 86 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 87 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   3m           88Mi            
on 88 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   3m           88Mi            
on 89 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   3m           88Mi            
on 90 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 91 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 92 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 93 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 94 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 95 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 96 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 97 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 98 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   1m           88Mi            
on 99 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi            
on 100 iteration
NAME                                        CPU(cores)   MEMORY(bytes)   
harvester-network-webhook-b5b67774b-zstfq   2m           88Mi     
```
And audited this:

https://user-images.githubusercontent.com/5370752/197631559-fb828714-576c-477d-ada2-7644abf7840b.mp4

This looks good :smile: :+1:  - I'll go ahead and close this out
