### ISSUE TITLE
[BUG] Two nodes upgrade failed in Pre-drained the first node then lost VIP connectivity

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3733]
**Describe the bug**

When we upgrade from v1.1.0 to v1.1.2-rc4, the process stuck in the `Pre-drained` the first node

* We notice the node 1 IP change to `192.168.50.34` instead of the original fixed IP `192.168.50.101`
The node 1 display error `kubelet stop posting node status`
![issue01](https://user-images.githubusercontent.com/29251855/228400484-37be947f-29c1-4231-b972-b7b73f420703.png)

* After a while, we lost the VIP connection to Harvester dashboard
![issue02](https://user-images.githubusercontent.com/29251855/228400668-62b7b311-4644-487f-a31e-dc71b53aaa6e.png)

* The console UI display Setting up Harvester and the Management URL is `Unavailable`
![issue03](https://user-images.githubusercontent.com/29251855/228400819-56b3292c-8dd3-49d6-ab36-87a996b56a68.png)

* We can still ssh to node 1 and node2, but unable to use kubectl command

**To Reproduce**
1. Prepare fixed node IP and VIP on dhcpd config file
2. Provision the two `v1.1.0` nodes Harvester on bare machines 
3. Create the vlan 1 network on management interface
4. Create a cluster network and network config bind on ens 7 and ens8
5. Create the vlan 101 network with manual route `192.168.101.0/24` , `192.168.101.253` 
6. Integrate Harvester to Rancher v2.6.11 and provision a RKE2 guest cluster
7. Set node and disk tag on Host page 
8. Create a new storage class and set as the default one 
9. Create three virtual machines separate on each node and use different network we created before 
10. Setup backup target 
11. Backup all VMs
12.  Perform offline upgrade to `v1.1.2-rc4` 

**Expected behavior**

Can successfully pass all upgrade process to the end without losing VIP connectivity. 

**Support bundle**

Failed to get support bundle since we lost the VIP connectivity 
Also the `k9s` and `kubelet` command not working on each node    

**Environment**
 - Harvester ISO version: v1.1.0 to v1.1.2-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): two nodes on bare machines

**Additional context**

- The network environment consist of one isc-dhcp service for handling Harvester installation config file 

  - IPv4 allocation range: 192.168.50.100 - 192.168.50.250  
  

- And one Asus Router to provide tagged vlan network 

  -  IPv4 allocation range: 192.168.50.2 - 192.168.50.100 
   
In the `/etc/dhcpd.conf`, we set fixed IP assignment of the following pattern 
  ```
  group {
    # create group
    if exists user-class and option user-class = "iPXE" {
      # iPXE Boot
      if option architecture-type = 00:07 {
        filename "http://192.168.50.76/ipxe-create-efi";
      } else {
        filename "http://192.168.50.76/ipxe-create";
      }
    } else {
      # PXE Boot
      if option architecture-type = 00:07 {
        # UEFI
        filename "ipxe.efi";
      } else {
        # Non-UEFI
        filename "undionly.kpxe";
      }
    }
  
    host node1 {
      hardware ethernet e4:54:e8:7c:f3:d4;
      fixed-address 192.168.50.101;
      server-name "node1";
  
    }
  
  }
  ```

**Comment by TachunLin** [comment]
* Here is the IP state on failed node 1 

```
node1:~ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp4s0f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:1b:21:38:57:30 brd ff:ff:ff:ff:ff:ff
3: eno1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master mgmt-bo state UP group default qlen 1000
    link/ether e4:54:e8:7c:f3:d4 brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
4: enp4s0f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:1b:21:38:57:31 brd ff:ff:ff:ff:ff:ff
5: enp179s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:1b:21:38:5c:78 brd ff:ff:ff:ff:ff:ff
6: enp179s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:1b:21:38:5c:79 brd ff:ff:ff:ff:ff:ff
7: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e4:54:e8:7c:f3:d4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.50.101/24 brd 192.168.50.255 scope global mgmt-br
       valid_lft forever preferred_lft forever
8: mgmt-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master mgmt-br state UP group default qlen 1000
    link/ether e4:54:e8:7c:f3:d4 brd ff:ff:ff:ff:ff:ff
```

* The dhcp server log 
```
Mar 28 15:53:50 localhost.localdomain dhcpd[2771]: DHCPREQUEST for 192.168.50.34 from e4:54:e8:7c:f3:d4 via eth2: lease 192.168.50.34 unavailable.
Mar 28 15:53:50 localhost.localdomain dhcpd[2771]: DHCPNAK on 192.168.50.34 to e4:54:e8:7c:f3:d4 via eth2
Mar 28 15:53:51 localhost.localdomain dhcpd[2771]: DHCPDISCOVER from e4:54:e8:7c:f3:d4 via eth2
Mar 28 15:53:51 localhost.localdomain dhcpd[2771]: DHCPOFFER on 192.168.50.101 to e4:54:e8:7c:f3:d4 via eth2
Mar 28 15:53:51 localhost.localdomain dhcpd[2771]: Dynamic and static leases present for 192.168.50.101.
Mar 28 15:53:51 localhost.localdomain dhcpd[2771]: Remove host declaration node1 or remove 192.168.50.101
Mar 28 15:53:51 localhost.localdomain dhcpd[2771]: from the dynamic address pool for 192.168.50.0/24
Mar 28 15:53:51 localhost.localdomain dhcpd[2771]: DHCPREQUEST for 192.168.50.101 (192.168.50.76) from e4:54:e8:7c:f3:d4 via eth2
Mar 28 15:53:51 localhost.localdomain dhcpd[2771]: DHCPACK on 192.168.50.101 to e4:54:e8:7c:f3:d4 via eth2
```

* The dhcp lease record on Asus RT-AC86U Router 
![image](https://user-images.githubusercontent.com/29251855/228404375-17d4e73c-4578-4e3d-9785-4773f49bfbfd.png)

**Comment by bk201** [comment]
The node initially has the IP `192.168.50.101` and after rebooting its IP is changed to `192.168.50.34`. Thus RKE2 can't start:
```
Mar 28 07:56:35 node1 rke2[2084]: time="2023-03-28T07:56:35Z" level=info msg="Defragmenting etcd database"
Mar 28 07:56:35 node1 rke2[2084]: time="2023-03-28T07:56:35Z" level=info msg="Waiting for etcd server to become available"
Mar 28 07:56:35 node1 rke2[2084]: time="2023-03-28T07:56:35Z" level=info msg="Waiting for API server to become available"
Mar 28 07:56:35 node1 rke2[2084]: time="2023-03-28T07:56:35Z" level=info msg="Tunnel server egress proxy waiting for runtime core to become available"
Mar 28 07:56:36 node1 rke2[2084]: time="2023-03-28T07:56:36Z" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Found [node1-babfd130=https://192.168.50.34:2380], expect: node1-babfd130=https://192.168.50.101:2380"
```

After fixing the network issue, the node has its IP back, but the etcd still can't start:
```
Mar 28 18:16:59 node1 rke2[26263]: time="2023-03-28T18:16:59Z" level=info msg="Starting rke2 v1.24.11+rke2r1 (23bdc987de9658eb80a5e03862ab34efdecf6d4e)"
Mar 28 18:16:59 node1 rke2[26263]: time="2023-03-28T18:16:59Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Mar 28 18:16:59 node1 rke2[26263]: time="2023-03-28T18:16:59Z" level=info msg="Starting temporary etcd to reconcile with datastore"
Mar 28 18:16:59 node1 rke2[26263]: {"level":"info","ts":"2023-03-28T18:16:59.495Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["http://127.0.0.1:2400
"]}
Mar 28 18:16:59 node1 rke2[26263]: {"level":"info","ts":"2023-03-28T18:16:59.495Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:
2399"]}
Mar 28 18:16:59 node1 rke2[26263]: {"level":"info","ts":"2023-03-28T18:16:59.495Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4","git-sha":"Not provide
d (use ./build instead of go build)","go-version":"go1.19.6 X:boringcrypto","go-os":"linux","go-arch":"amd64","max-cpu-set":8,"max-cpu-available":8,"member-initialized":true,"name":"node1-b
abfd130","data-dir":"/var/lib/rancher/rke2/server/db/etcd-tmp","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/rke2/server/db/etcd-tmp/member","force-new-cluster":true,"h
eartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":10000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://127.0.0
.1:2400"],"listen-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[],"cors":["*"]
,"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":true,"corrupt-che
ck-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
Mar 28 18:16:59 node1 rke2[26263]: {"level":"info","ts":"2023-03-28T18:16:59.541Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/lib/rancher/rke2/server/db/etcd
-tmp/member/snap/db","took":"45.458124ms"}
Mar 28 18:17:00 node1 rke2[26263]: {"level":"info","ts":"2023-03-28T18:17:00.184Z","caller":"etcdserver/server.go:508","msg":"recovered v2 store from snapshot","snapshot-index":140015,"snap
shot-size":"7.5 kB"}
Mar 28 18:17:00 node1 rke2[26263]: {"level":"warn","ts":"2023-03-28T18:17:00.197Z","caller":"snap/db.go:88","msg":"failed to find [SNAPSHOT-INDEX].snap.db","snapshot-index":140015,"snapshot
-file-path":"/var/lib/rancher/rke2/server/db/etcd-tmp/member/snap/00000000000222ef.snap.db","error":"snap: snapshot file doesn't exist"}
Mar 28 18:17:00 node1 rke2[26263]: {"level":"panic","ts":"2023-03-28T18:17:00.197Z","caller":"etcdserver/server.go:515","msg":"failed to recover v3 backend from snapshot","error":"failed to
 find database snapshot file (snap: snapshot file doesn't exist)","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver.NewServer\n\t/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.4-k3s1/et
cdserver/server.go:515\ngo.etcd.io/etcd/server/v3/embed.StartEtcd\n\t/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.4-k3s1/embed/etcd.go:245\ngithub.com/k3s-io/k3s/pkg/daemons/executor.(
*Embedded).ETCD\n\t/go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/daemons/executor/etcd.go:30\ngithub.com/k3s-io/k3s/pkg/etcd.(*ETCD).StartEmbeddedTemporary\n\
t/go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/etcd/etcd.go:890\ngithub.com/k3s-io/k3s/pkg/cluster.(*Cluster).reconcileEtcd\n\t/go/pkg/mod/github.com/k3s-io/k
3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/cluster/bootstrap.go:523\ngithub.com/k3s-io/k3s/pkg/cluster.(*Cluster).Bootstrap\n\t/go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922
-74ed4bef6191/pkg/cluster/bootstrap.go:63\ngithub.com/k3s-io/k3s/pkg/daemons/control.prepare\n\t/go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/daemons/control/
server.go:267\ngithub.com/k3s-io/k3s/pkg/daemons/control.Server\n\t/go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/daemons/control/server.go:34\ngithub.com/k3s-
io/k3s/pkg/server.StartServer\n\t/go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/server/server.go:59\ngithub.com/k3s-io/k3s/pkg/cli/server.run\n\t/go/pkg/mod/gi
thub.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/cli/server/server.go:459\ngithub.com/k3s-io/k3s/pkg/cli/server.RunWithControllers\n\t/go/pkg/mod/github.com/k3s-io/k3s@v1.24.1
1-0.20230214211922-74ed4bef6191/pkg/cli/server/server.go:46\ngithub.com/rancher/rke2/pkg/rke2.Server\n\t/source/pkg/rke2/rke2.go:123\ngithub.com/rancher/rke2/pkg/cli/cmds.ServerRun\n\t/sour
ce/pkg/cli/cmds/server.go:162\ngithub.com/urfave/cli.HandleAction\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524\ngithub.com/urfave/cli.Command.Run\n\t/go/pkg/mod/github.com/urfave
/cli@v1.22.9/command.go:173\ngithub.com/urfave/cli.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:277\nmain.main\n\t/source/main.go:23\nruntime.main\n\t/usr/local/go/src/run
time/proc.go:250"}
Mar 28 18:17:00 node1 rke2[26263]: panic: failed to recover v3 backend from snapshot
Mar 28 18:17:00 node1 rke2[26263]: goroutine 1 [running]:
Mar 28 18:17:00 node1 rke2[26263]: go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x0?, {0x0?, 0x0?, 0xc00098e220?})
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
Mar 28 18:17:00 node1 rke2[26263]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000306c30, {0xc0003cabc0, 0x1, 0x1})
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
Mar 28 18:17:00 node1 rke2[26263]: go.uber.org/zap.(*Logger).Panic(0xc00091e000?, {0x31dba17?, 0x0?}, {0xc0003cabc0, 0x1, 0x1})
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
Mar 28 18:17:00 node1 rke2[26263]: go.etcd.io/etcd/server/v3/etcdserver.NewServer({{0xc00091e000, 0xe}, {0x0, 0x0}, {0x0, 0x0}, {0xc000830510, 0x1, 0x1}, {0xc0008303f0, ...}, ...})
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.4-k3s1/etcdserver/server.go:515 +0x1d85
Mar 28 18:17:00 node1 rke2[26263]: go.etcd.io/etcd/server/v3/embed.StartEtcd(0xc000378e00)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.4-k3s1/embed/etcd.go:245 +0x1178
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/daemons/executor.(*Embedded).ETCD(_, {_, _}, {{{0xc00005c2b8, 0x15}, {0x0, 0x0}, {0x0, 0x0}}, {0xc000510470, ...}, ...}, ...)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/daemons/executor/etcd.go:30 +0x10e
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/etcd.(*ETCD).StartEmbeddedTemporary(0xc00098c000, {0x3672b98, 0xc00063bbc0})
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/etcd/etcd.go:890 +0x55b
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/cluster.(*Cluster).reconcileEtcd(0xc0005e4030, {0x3672b98, 0xc0003cb100})
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/cluster/bootstrap.go:523 +0x2a5
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/cluster.(*Cluster).Bootstrap(0xc0005e4030, {0x3672b98, 0xc0003cb100}, 0x0)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/cluster/bootstrap.go:63 +0x1e5
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/daemons/control.prepare({0x3672b98, 0xc0003cb100}, 0xc00064d408)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/daemons/control/server.go:267 +0x245
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/daemons/control.Server({0x3672b98?, 0xc0003cb100}, 0xc00064d408)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/daemons/control/server.go:34 +0xff
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/server.StartServer({0x3672b98?, 0xc0003cb100}, 0xc00064d400, 0x1?)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/server/server.go:59 +0x93
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/cli/server.run(0xc000397ce0, 0x4faa900, {0x0, 0x0, 0x9?}, {0xc000a4c878, 0x0, 0x0?})
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/cli/server/server.go:459 +0x2b71
Mar 28 18:17:00 node1 rke2[26263]: github.com/k3s-io/k3s/pkg/cli/server.RunWithControllers(...)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/k3s-io/k3s@v1.24.11-0.20230214211922-74ed4bef6191/pkg/cli/server/server.go:46
Mar 28 18:17:00 node1 rke2[26263]: github.com/rancher/rke2/pkg/rke2.Server(_, {{0xc0003b2f14, 0x43}, {0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {0x0, ...}, ...}, ...})
Mar 28 18:17:00 node1 rke2[26263]:         /source/pkg/rke2/rke2.go:123 +0x545
Mar 28 18:17:00 node1 rke2[26263]: github.com/rancher/rke2/pkg/cli/cmds.ServerRun(0xc000397ce0?)
Mar 28 18:17:00 node1 rke2[26263]:         /source/pkg/cli/cmds/server.go:162 +0xa5
Mar 28 18:17:00 node1 rke2[26263]: github.com/urfave/cli.HandleAction({0x2bbe200?, 0x32f4168?}, 0x6?)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:524 +0x50
Mar 28 18:17:00 node1 rke2[26263]: github.com/urfave/cli.Command.Run({{0x31624b4, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x318d6e0, 0x15}, {0xc000610768, ...}, ...}, ...)
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/urfave/cli@v1.22.9/command.go:173 +0x65b
Mar 28 18:17:00 node1 rke2[26263]: github.com/urfave/cli.(*App).Run(0xc000afea80, {0xc0000b4d80, 0x11, 0x12})
Mar 28 18:17:00 node1 rke2[26263]:         /go/pkg/mod/github.com/urfave/cli@v1.22.9/app.go:277 +0x8a7
Mar 28 18:17:00 node1 rke2[26263]: main.main()
Mar 28 18:17:00 node1 rke2[26263]:         /source/main.go:23 +0xb3e
Mar 28 18:17:00 node1 systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 28 18:17:00 node1 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Mar 28 18:17:00 node1 systemd[1]: rke2-server.service: Unit process 2307 (containerd-shim) remains running after unit stopped.
Mar 28 18:17:00 node1 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
Mar 28 18:17:05 node1 systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 42.
Mar 28 18:17:05 node1 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
```
