### ISSUE TITLE
backend crash

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#38]
```E0813 10:50:26.479429       6 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 590 [running]:
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1800d20, 0x2b39d20)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1800d20, 0x2b39d20)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/harvester/pkg/controller/master/template.(*templateHandler).OnChanged(0xc000415320, 0xc00213a0a0, 0x18, 0x0, 0x7265736572703a66, 0x203000, 0x2273646c6569466e)
	/go/src/github.com/rancher/harvester/pkg/controller/master/template/template_controller.go:16 +0x26
github.com/rancher/harvester/pkg/generated/controllers/vm.cattle.io/v1alpha1.FromTemplateHandlerToHandler.func1(0xc00213a0a0, 0x18, 0x0, 0x0, 0x19b07e0, 0x697461746f6e6e61, 0x7b3a22736e6f, 0x60)
	/go/src/github.com/rancher/harvester/pkg/generated/controllers/vm.cattle.io/v1alpha1/template.go:103 +0xdb
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0003f2b80, 0xc00213a0a0, 0x18, 0x0, 0x0, 0x65697061225c3a22, 0x408c5b, 0x1afa3a0, 0xc000217320)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0007140f0, 0xc00213a0a0, 0x18, 0x0, 0x0, 0x42d200, 0x0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000324fd0, 0xc00213a0a0, 0x18, 0xc000a794d0, 0xc000bdad30)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:208 +0x122
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000324fd0, 0x176d800, 0xc00271e610, 0x0, 0x0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:193 +0xf0
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000324fd0, 0xc000ba2e40)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:170 +0x51
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000324fd0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:159 +0x2b
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0007494b0)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0007494b0, 0x1c8c640, 0xc000648000, 0xc000bd4001, 0xc0000e2420)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007494b0, 0x3b9aca00, 0x0, 0x3a2265706f637301, 0xc0000e2420)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0007494b0, 0x3b9aca00, 0xc0000e2420)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:130 +0x35e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x15b1066]
goroutine 590 [running]:
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1800d20, 0x2b39d20)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/rancher/harvester/pkg/controller/master/template.(*templateHandler).OnChanged(0xc000415320, 0xc00213a0a0, 0x18, 0x0, 0x7265736572703a66, 0x203000, 0x2273646c6569466e)
	/go/src/github.com/rancher/harvester/pkg/controller/master/template/template_controller.go:16 +0x26
github.com/rancher/harvester/pkg/generated/controllers/vm.cattle.io/v1alpha1.FromTemplateHandlerToHandler.func1(0xc00213a0a0, 0x18, 0x0, 0x0, 0x19b07e0, 0x697461746f6e6e61, 0x7b3a22736e6f, 0x60)
	/go/src/github.com/rancher/harvester/pkg/generated/controllers/vm.cattle.io/v1alpha1/template.go:103 +0xdb
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0003f2b80, 0xc00213a0a0, 0x18, 0x0, 0x0, 0x65697061225c3a22, 0x408c5b, 0x1afa3a0, 0xc000217320)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc0007140f0, 0xc00213a0a0, 0x18, 0x0, 0x0, 0x42d200, 0x0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000324fd0, 0xc00213a0a0, 0x18, 0xc000a794d0, 0xc000bdad30)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:208 +0x122
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000324fd0, 0x176d800, 0xc00271e610, 0x0, 0x0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:193 +0xf0
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000324fd0, 0xc000ba2e40)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:170 +0x51
github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000324fd0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:159 +0x2b
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0007494b0)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0007494b0, 0x1c8c640, 0xc000648000, 0xc000bd4001, 0xc0000e2420)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007494b0, 0x3b9aca00, 0x0, 0x3a2265706f637301, 0xc0000e2420)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0007494b0, 0x3b9aca00, 0xc0000e2420)
	/go/src/github.com/rancher/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:130 +0x35e
```

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/39

**Comment by guangbochen** [comment]
close in favor of #39
