### ISSUE TITLE
[BUG] Harvester encounters panic on rancher apiserver

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4157]
**Describe the bug**

When debugging PR https://github.com/harvester/harvester/pull/4127, Harvester encounters panic on rancher apiserver several times.

```
2023/06/29 12:58:46 http: panic serving pipe: runtime error: invalid memory address or nil pointer dereference
goroutine 20515 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x24362a0, 0x47f8500})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/server.(*Server).handle(0xc0051c6d20, 0xc00f3bc0f0, 0xc00f3bc0f0?)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/server/server.go:154 +0x894
github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/server.(*Server).Handle(...)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/server/server.go:101
github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/server/handler.(*apiServer).apiHandler.func1({0x2db8d28?, 0xc005fa0460?}, 0x2d8f701?)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/server/handler/apiserver.go:98 +0x8c
net/http.HandlerFunc.ServeHTTP(0x2dba070?, {0x2db8d28?, 0xc005fa0460?}, 0x2d8f7f0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1({0x2db8d28, 0xc005fa0460}, 0xc0078b6b00)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/auth/filter.go:172 +0x436
net/http.HandlerFunc.ServeHTTP(0xc00defb770?, {0x2db8d28?, 0xc005fa0460?}, 0xc011f81878?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/urlbuilder.RedirectRewrite.func1({0x2db8d28?, 0xc005fa0460}, 0xc0078b6b00)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/urlbuilder/redirect.go:14 +0x15c
net/http.HandlerFunc.ServeHTTP(0xc0078b6a00?, {0x2db8d28?, 0xc005fa0460?}, 0x203003?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/harvester/harvester/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc004eb2480, {0x2db8d28, 0xc005fa0460}, 0xc0078b6900)
	/go/src/github.com/harvester/harvester/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf
github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/auth.ToMiddleware.func1.1({0x2db8d28, 0xc005fa0460}, 0xc009050000)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/auth/filter.go:172 +0x436
net/http.HandlerFunc.ServeHTTP(0x0?, {0x2db8d28?, 0xc005fa0460?}, 0x40d6a5?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0x2da6b60?}, {0x2db8d28, 0xc005fa0460}, 0xc009050000)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00a7e1f40, {0x2dba070, 0xc0062450b0})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
harv41:/home/rancher # 
```

**To Reproduce**
1. Restart Harvester POD frequently, there are chances to hit this issue

**Expected behavior**

No panic

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.2.0 master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM VM based Harvester cluster

**Additional context**

**Comment by w13915984028** [comment]
The upstream issue: https://github.com/rancher/rancher/issues/40296
upstream fix: https://github.com/rancher/apiserver/pull/23

Rancher bump apiserver: in https://github.com/rancher/rancher/pull/41653

> @[JonCrowther](https://github.com/JonCrowther) JonCrowther merged commit [ec9a803](https://github.com/rancher/rancher/commit/ec9a803b9e5663d75877fc667d7f815d81410349) into rancher:release/v2.7 [on May 30](https://github.com/rancher/rancher/pull/41653#event-9379460285)

Harvester v1.2.0 needs to check if the used Rancher includes this fix.

cc @guangbochen

**Comment by guangbochen** [comment]
cc @bk201, we might be able to cover this via https://github.com/harvester/harvester-installer/pull/518

**Comment by guangbochen** [comment]
@w13915984028 can u please help to share your debug steps, so we can reproduce the testing steps and verify whether this is fixed in the newer Rancher v2.7.5, thanks.
