### ISSUE TITLE
[BUG] pod back-off restart

### ISSUE THREAD

**Issue by incubator4** [harvester/harvester#427]
**Describe the bug**
after operate vm,harvester pod got error

**Logs**

after init message
```
time="2021-01-14T05:59:05Z" level=info msg="APIVersion longhorn.io/v1beta1 Kind ShareManager"
time="2021-01-14T05:59:05Z" level=info msg="APIVersion longhorn.io/v1beta1 Kind InstanceManager"
time="2021-01-14T05:59:05Z" level=info msg="APIVersion metrics.k8s.io/v1beta1 Kind NodeMetrics"
time="2021-01-14T05:59:05Z" level=info msg="APIVersion metrics.k8s.io/v1beta1 Kind PodMetrics"
time="2021-01-14T05:59:08Z" level=info msg="Refreshing all schemas"
fatal error: concurrent map read and map write

goroutine 3776 [running]:
runtime.throw(0x1bb96cf, 0x21)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000c6c658 sp=0xc000c6c628 pc=0x42e4b2
runtime.mapaccess2_faststr(0x18f7180, 0xc0030d4f30, 0x1b92e82, 0x6, 0xc000c6c728, 0x1c60d01)
	/usr/local/go/src/runtime/map_faststr.go:116 +0x48f fp=0xc000c6c6c8 sp=0xc000c6c658 pc=0x412bef
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/types.(*APISchemas).LookupSchema(0xc000c94d60, 0x1b92e82, 0x6, 0xc000c6c728)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/types/schemas.go:117 +0x53 fp=0xc000c6c708 sp=0xc000c6c6c8 pc=0x1478963
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/writer.(*EncodingResponseWriter).convert(0xc00277c000, 0xc0017123c0, 0x1b92e82, 0x6, 0xc0020af8c0, 0x3d, 0x1941d20, 0xc0058e8690, 0x10)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/writer/encoding.go:59 +0x50 fp=0xc000c6c780 sp=0xc000c6c708 pc=0x147e980
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/writer.(*EncodingResponseWriter).Body(0xc00277c000, 0xc0017123c0, 0x0, 0x0, 0x1b92e82, 0x6, 0xc0020af8c0, 0x3d, 0x1941d20, 0xc0058e8690, ...)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/writer/encoding.go:33 +0x5d fp=0xc000c6c7d8 sp=0xc000c6c780 pc=0x147e53d
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe.(*Converter).ToAPIObject(0xc00277c000, 0x1b92e82, 0x6, 0xc0020af8c0, 0x3d, 0x1941d20, 0xc0058e8690, 0x0, 0x0, 0x203000, ...)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe/convert.go:44 +0x95 fp=0xc000c6c888 sp=0xc000c6c7d8 pc=0x14c1335
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe.MarshallObject(0xc0017123c0, 0x1b9f568, 0xf, 0x1b92e82, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe/convert.go:21 +0x95 fp=0xc000c6c8f0 sp=0xc000c6c888 pc=0x14c10c5
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe.writeData(0xc0017123c0, 0xc0016366e0, 0x1b9f568, 0xf, 0x1b92e82, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe/handler.go:70 +0x6e fp=0xc000c6cba0 sp=0xc000c6c8f0 pc=0x14c1b3e
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe.handler(0xc0017123c0, 0x0, 0x0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe/handler.go:58 +0x2f3 fp=0xc000c6cee0 sp=0xc000c6cba0 pc=0x14c1973
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe.Handler(0xc0017123c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00305f480, 0x0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/subscribe/handler.go:31 +0x4d fp=0xc000c6cf38 sp=0xc000c6cee0 pc=0x14c159d
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/server.handleList(0xc0017123c0, 0x1c611d0, 0x1c61170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/server/server.go:210 +0x78 fp=0xc000c6d008 sp=0xc000c6cf38 pc=0x14c6208
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/server.(*Server).handleOp(0xc000a48ae0, 0xc0017123c0, 0xc000c6d448, 0x4, 0xc00023ebd8, 0x203000, 0x203000)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/server/server.go:187 +0x2d0 fp=0xc000c6d278 sp=0xc000c6d008 pc=0x14c5970
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/server.(*Server).handle(0xc000a48ae0, 0xc0017123c0, 0x1c611a0)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/server/server.go:149 +0x29c fp=0xc000c6d4b8 sp=0xc000c6d278 pc=0x14c4f8c
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/server.(*Server).Handle(...)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/server/server.go:109
github.com/rancher/harvester/vendor/github.com/rancher/steve/pkg/server/handler.(*apiServer).api(0xc000588be0, 0x1e59e80, 0xc00156ca80, 0xc000739300, 0x1c61340)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/steve/pkg/server/handler/apiserver.go:108 +0x83 fp=0xc000c6d500 sp=0xc000c6d4b8 pc=0x1641fd3
github.com/rancher/harvester/vendor/github.com/rancher/steve/pkg/server/handler.(*apiServer).apiHandler.func1(0x1e59e80, 0xc00156ca80, 0xc000739300)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/steve/pkg/server/handler/apiserver.go:98 +0x51 fp=0xc000c6d538 sp=0xc000c6d500 pc=0x1642421
net/http.HandlerFunc.ServeHTTP(0xc000588c20, 0x1e59e80, 0xc00156ca80, 0xc000739300)
	/usr/local/go/src/net/http/server.go:2036 +0x44 fp=0xc000c6d560 sp=0xc000c6d538 pc=0x81a054
github.com/rancher/harvester/pkg/api/auth.(*Middleware).AuthMiddleware(0xc000a08050, 0x1e59e80, 0xc00156ca80, 0xc000739100, 0x1e1b900, 0xc000588c20)
	/go/src/github.com/rancher/harvester/pkg/api/auth/auth_handler.go:47 +0x323 fp=0xc000c6d5f8 sp=0xc000c6d560 pc=0x1468cf3
github.com/rancher/harvester/pkg/api/auth.(*Middleware).AuthMiddleware-fm(0x1e59e80, 0xc00156ca80, 0xc000739100, 0x1e1b900, 0xc000588c20)
	/go/src/github.com/rancher/harvester/pkg/api/auth/auth_handler.go:30 +0x5c fp=0xc000c6d638 sp=0xc000c6d5f8 pc=0x176aa2c
github.com/rancher/harvester/vendor/github.com/rancher/steve/pkg/auth.Middleware.Wrap.func1(0x1e59e80, 0xc00156ca80, 0xc000739100)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/steve/pkg/auth/filter.go:36 +0x55 fp=0xc000c6d670 sp=0xc000c6d638 pc=0x15c3ed5
net/http.HandlerFunc.ServeHTTP(0xc000588c40, 0x1e59e80, 0xc00156ca80, 0xc000739100)
	/usr/local/go/src/net/http/server.go:2036 +0x44 fp=0xc000c6d698 sp=0xc000c6d670 pc=0x81a054
github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/urlbuilder.RedirectRewrite.func1(0x1e59e80, 0xc00156ca80, 0xc000739100)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/apiserver/pkg/urlbuilder/redirect.go:14 +0x1cc fp=0xc000c6d700 sp=0xc000c6d698 pc=0x147d11c
net/http.HandlerFunc.ServeHTTP(0xc0010b5180, 0x1e59e80, 0xc00156ca80, 0xc000739100)
	/usr/local/go/src/net/http/server.go:2036 +0x44 fp=0xc000c6d728 sp=0xc000c6d700 pc=0x81a054
github.com/rancher/harvester/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000a5a3c0, 0x1e59e80, 0xc00156ca80, 0xc000738f00)
	/go/src/github.com/rancher/harvester/vendor/github.com/gorilla/mux/mux.go:210 +0xe2 fp=0xc000c6d850 sp=0xc000c6d728 pc=0x146db52
github.com/rancher/harvester/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000a5a300, 0x1e59e80, 0xc00156ca80, 0xc000738c00)
	/go/src/github.com/rancher/harvester/vendor/github.com/gorilla/mux/mux.go:210 +0xe2 fp=0xc000c6d978 sp=0xc000c6d850 pc=0x146db52
github.com/rancher/harvester/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000a5a480, 0x1e59e80, 0xc00156ca80, 0xc000738900)
	/go/src/github.com/rancher/harvester/vendor/github.com/gorilla/mux/mux.go:210 +0xe2 fp=0xc000c6daa0 sp=0xc000c6d978 pc=0x146db52
github.com/rancher/harvester/vendor/github.com/rancher/steve/pkg/dashboard.Route.func2(0x1e59e80, 0xc00156ca80, 0xc000738900)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/steve/pkg/dashboard/ui.go:55 +0xe5 fp=0xc000c6dae8 sp=0xc000c6daa0 pc=0x1607ce5
net/http.HandlerFunc.ServeHTTP(0xc0006c5b10, 0x1e59e80, 0xc00156ca80, 0xc000738900)
	/usr/local/go/src/net/http/server.go:2036 +0x44 fp=0xc000c6db10 sp=0xc000c6dae8 pc=0x81a054
github.com/rancher/harvester/vendor/github.com/rancher/dynamiclistener/server.wrapHandler.func1(0x1e59e80, 0xc00156ca80, 0xc000738900)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/dynamiclistener/server/server.go:187 +0x95 fp=0xc000c6db50 sp=0xc000c6db10 pc=0x14a9245
net/http.HandlerFunc.ServeHTTP(0xc000c96270, 0x1e59e80, 0xc00156ca80, 0xc000738900)
	/usr/local/go/src/net/http/server.go:2036 +0x44 fp=0xc000c6db78 sp=0xc000c6db50 pc=0x81a054
github.com/rancher/harvester/vendor/github.com/rancher/dynamiclistener.HTTPRedirect.func1(0x1e59e80, 0xc00156ca80, 0xc000738900)
	/go/src/github.com/rancher/harvester/vendor/github.com/rancher/dynamiclistener/redirect.go:20 +0x221 fp=0xc000c6dbf0 sp=0xc000c6db78 pc=0x1487121
net/http.HandlerFunc.ServeHTTP(0xc0032022c0, 0x1e59e80, 0xc00156ca80, 0xc000738900)
	/usr/local/go/src/net/http/server.go:2036 +0x44 fp=0xc000c6dc18 sp=0xc000c6dbf0 pc=0x81a054
net/http.serverHandler.ServeHTTP(0xc001fd2380, 0x1e59e80, 0xc00156ca80, 0xc000738900)
	/usr/local/go/src/net/http/server.go:2831 +0xa4 fp=0xc000c6dc48 sp=0xc000c6dc18 pc=0x81d4a4
net/http.(*conn).serve(0xc00300a780, 0x1e64a40, 0xc000927040)
	/usr/local/go/src/net/http/server.go:1919 +0x875 fp=0xc000c6dfc8 sp=0xc000c6dc48 pc=0x818e45
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000c6dfd0 sp=0xc000c6dfc8 pc=0x45b681
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2957 +0x384

```

**Environment:**
 - Harvester Helm Chart 0.1: 
 - RKE v1.19.2

**Comment by guangbochen** [comment]
this issue should be addressed in the master version with API server bump of https://github.com/rancher/harvester/pull/414, will keep my eyes on it.

**Comment by DoNotSayYes** [comment]
Validated on master-head
**Steps:**
1. Create a VM
2. Restart it
3. Login in it

**Result:**
No similar error messages were encountered
