### ISSUE TITLE
[BUG] Upgrade of fairly fresh 1.1.2 cluster to 1.2.0 stuck in upgrading system service phase

### ISSUE THREAD

**Issue by oivindoh** [harvester/harvester#4513]
**Describe the bug**
1.1.2 cluster can't upgrade to 1.2.0 due to being out of space on /var/lib/kubevirt on one of the hosts

**To Reproduce**

1. Start Harvester 1.2.0 upgrade from GUI on a 32GiB system cluster
2. Wait for all jobs prior to applying manifests job to complete successfully and apply manifests job to start
3. Observe fleet bundles settling:

```
1:/home/rancher # kubectl get bundle -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1
fleet-local   local-managed-system-agent                    1/1
fleet-local   mcc-harvester                                 1/1
fleet-local   mcc-harvester-crd                             1/1
fleet-local   mcc-local-managed-system-upgrade-controller   1/1
fleet-local   mcc-rancher-logging                           0/1                       OutOfSync(1) [Cluster fleet-local/local]
fleet-local   mcc-rancher-logging-crd                       0/1                       OutOfSync(1) [Cluster fleet-local/local]
fleet-local   mcc-rancher-monitoring                        0/1                       OutOfSync(1) [Cluster fleet-local/local]
fleet-local   mcc-rancher-monitoring-crd                    0/1                       OutOfSync(1) [Cluster fleet-local/local]
```

4. Observe apply manifests job log settle to just endless repeat of this (job has now been running for 90 minutes, mostly just spamming the following log message):

```
1:/home/rancher # kubectl logs -n harvester-system hvst-upgrade-4rf9v-apply-manifests-kp4lz |tail
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
```

Start of apply manifests log:

```
1:/home/rancher # kubectl logs -n harvester-system hvst-upgrade-4rf9v-apply-manifests-kp4lz |head
harvester: v1.2.0
harvesterChart: 1.2.0
os: Harvester v1.2.0
kubernetes: v1.25.9+rke2r1
rancher: v2.7.5
monitoringChart: 102.0.0+up40.1.2
loggingChart: 102.0.0+up3.17.10
kubevirt: 0.54.0-150400.3.19.1
minUpgradableVersion: 'v1.1.2'
rancherDependencies:
```

Start of kubevirt log messages:

```
Waiting for ManagedChart fleet-local/harvester from generation 2
Target version: 1.2.0, Target state: ready
Current version: 1.2.0, Current state: OutOfSync, Current generation: 2
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: WaitApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: WaitApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: WaitApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: WaitApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: WaitApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: WaitApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: ErrApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: ErrApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: ErrApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: ErrApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: ErrApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: ErrApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: ErrApplied, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: NotReady, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: NotReady, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: NotReady, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: NotReady, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: NotReady, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: NotReady, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: NotReady, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: NotReady, Current generation: 4
Sleep for 5 seconds to retry
Current version: 1.2.0, Current state: null, Current generation: 4
Waiting for ManagedChart fleet-local/harvester-crd from generation 2
Target version: 1.2.0, Target state: ready
Current version: 1.2.0, Current state: null, Current generation: 4
Waiting for KubeVirt to upgraded to 0.54.0-150400.3.19.1...
KubeVirt current version: 0.54.0-150400.3.10.4, target version: 0.54.0-150400.3.19.1
```

The virt-handler pod on one of the nodes is in CrashLoopBackOff due to being out of disk space:

```
kubectl -n harvester-system logs virt-handler-bftd8
Defaulted container "virt-handler" out of: virt-handler, virt-launcher (init)
{"component":"virt-handler","hostname":"2","level":"info","pos":"virt-handler.go:196","timestamp":"2023-09-11T10:01:29.764069Z"}
panic: failed to copy file: write /var/lib/kubevirt/init/usr/bin/container-disk: copy_file_range: no space left on device

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000320000)
    /home/abuild/rpmbuild/BUILD/kubevirt-0.54.0/go/src/kubevirt.io/kubevirt/cmd/virt-handler/virt-handler.go:207 +0x2b15
main.main()
    /home/abuild/rpmbuild/BUILD/kubevirt-0.54.0/go/src/kubevirt.io/kubevirt/cmd/virt-handler/virt-handler.go:611 +0x54
```

This node only has 32GB memory (test system), and /var appears to be an overlay fs based on 25% of available memory.

This mount appears to be filled with rke2 snapshots.

**Expected behavior**

Upgrade should complete successfully, with information exposed as to what's going on clearly exposed in the UI.

If 32GB is not at all supported, reflect that in notes.

**Support bundle**
<!--

zstd tar file due to .zip size issues with github: [bundle.tgz](https://github.com/harvester/harvester/files/12574930/bundle.tgz)

**Environment**
 - Harvester ISO version: 1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal Lenovo

**Comment by bk201** [comment]
@oivindoh can you check the free space of `/usr/local` in the host? containers storage is allocated under it by default.

**Comment by oivindoh** [comment]
@bk201 the machine is down for adding more memory now, but prior to shutting it down:

```
/dev/sda5                                                98G   59G   35G  64% /usr/local
overlay                                                 7.8G  7.8G     0 100% /var
```

The /var/lib/kubevirt path appears to be the source of our woes

```
  - hostPath:
      path: /var/lib/kubevirt
      type: ""
```

**Comment by bk201** [comment]
@oivindoh Thanks, can you help identify what's occupying /var? I did a quick search and found this:
```
du -a /run/overlay/var.overlay/upper | sort -n -r | head -n 20
```

**Comment by oivindoh** [comment]
Unfortunately all gone since it was rebooted. I struggled a bit figuring out how to fetch this prior to reboot, but failed to produce the command above.

The below is executed after the apply-manifest has restarted after reboot for more memory. I'm keeping an eye in a watch to see if things change, but so far this is pretty static:

```
du -ah /run/overlay/var.overlay/upper | sort -h -r | head -n 20                                                                                                                                                                
3.0M    /run/overlay/var.overlay/upper/lib
3.0M    /run/overlay/var.overlay/upper
1.5M    /run/overlay/var.overlay/upper/lib/ca-certificates
916K    /run/overlay/var.overlay/upper/lib/kubevirt/init/usr/bin/container-disk
916K    /run/overlay/var.overlay/upper/lib/kubevirt/init/usr/bin
916K    /run/overlay/var.overlay/upper/lib/kubevirt/init/usr
916K    /run/overlay/var.overlay/upper/lib/kubevirt/init
916K    /run/overlay/var.overlay/upper/lib/kubevirt
624K    /run/overlay/var.overlay/upper/lib/ca-certificates/openssl
548K    /run/overlay/var.overlay/upper/lib/ca-certificates/pem
364K    /run/overlay/var.overlay/upper/lib/kubevirt-node-labeller
332K    /run/overlay/var.overlay/upper/lib/kubevirt-node-labeller/cpu_map
208K    /run/overlay/var.overlay/upper/lib/ca-certificates/ca-bundle.pem
164K    /run/overlay/var.overlay/upper/lib/systemd
160K    /run/overlay/var.overlay/upper/lib/systemd/catalog/database
160K    /run/overlay/var.overlay/upper/lib/systemd/catalog
152K    /run/overlay/var.overlay/upper/lib/ca-certificates/java-cacerts
20K     /run/overlay/var.overlay/upper/lib/kubevirt-node-labeller/cpu_map/x86_features.xml
16K     /run/overlay/var.overlay/upper/lib/smartmontools
12K     /run/overlay/var.overlay/upper/lib/kubevirt-node-labeller/virsh_domcapabilities.xml
```

Looking at nodes in another environment running 1.1.2 I see nothing too far off these numbers there either.

**Comment by oivindoh** [comment]
The upgrade went through just fine after reboot with enough memory. As there's no useful information to be had as to what filled /var after the system restart, I guess I should just close this.
