### ISSUE TITLE
[BUG] nil pointer error of tls in the dynamiclister

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#592]
**Describe the bug**
runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 671 [running]:

```
E0326 13:14:13.384964   82424 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 671 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2e55b00, 0x4b59e90)
        /Users/guangbochen/src/ranchervm/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /Users/guangbochen/src/ranchervm/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x2e55b00, 0x4b59e90)
        /usr/local/Cellar/go@1.13/1.13.15/libexec/src/runtime/panic.go:679 +0x1b2
github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).saveInK8s(0xc000c7c690, 0xc001f46400, 0x0, 0xc002189a78, 0x100eb68)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:144 +0xae
github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).Update(0xc000c7c690, 0xc001f46400, 0x0, 0x0)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:170 +0xb5
github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).init.func1(0xc002910280, 0x18, 0xc001f46400, 0xc001f46400, 0x0, 0x0)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:83 +0x95
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1(0xc002910280, 0x18, 0x35cb080, 0xc001f46400, 0x35cb080, 0xc001f46400, 0x0, 0x0)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/wrangler/pkg/generated/controllers/core/v1/secret.go:102 +0x65
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc000601480, 0xc002910280, 0x18, 0x35cb080, 0xc001f46400, 0x35cb080, 0xc001f46400, 0x0, 0x0)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000d17b30, 0xc002910280, 0x18, 0x35cb080, 0xc001f46400, 0x1030001, 0x0)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0007600b0, 0xc002910280, 0x18, 0xc001508060, 0xc002189d40)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0007600b0, 0x2d40fe0, 0xc0006014b0, 0x0, 0x0)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:192 +0xf0
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0007600b0, 0x1)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0007600b0)
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000986b70)
        /Users/guangbochen/src/ranchervm/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000986b70, 0x35ae240, 0xc0015d0390, 0x1, 0xc0000c0180)
        /Users/guangbochen/src/ranchervm/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000986b70, 0x3b9aca00, 0x0, 0x1, 0xc0000c0180)
        /Users/guangbochen/src/ranchervm/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc000986b70, 0x3b9aca00, 0xc0000c0180)
        /Users/guangbochen/src/ranchervm/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /Users/guangbochen/src/ranchervm/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:129 +0x35e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x28ab93e]

```

**To Reproduce**
1. run master harvester without rancher integration environment will be failed on a nil pointer exception

**Environment:**
 - Harvester ISO version: app mode using latest master
 - Installation Mode: app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
**Environment:**
 - Harvester ISO version: master-dcf0b550-head
 - Installation Mode: app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
 
**Steps**
1. create rke cluster
2. Use Helm to install
![image](https://user-images.githubusercontent.com/15829074/113128661-a0ed2d00-924c-11eb-8fe3-1c7f75a376b0.png)

**Results**
1. Use command `kubectl logs -f harvester-6864797b95-5v9t6 -n harvester-system`, no error reported
2. Harvester access is normal
![image](https://user-images.githubusercontent.com/15829074/113131869-52419200-9250-11eb-903f-df6a4b909ad4.png)
