### ISSUE TITLE
[BUG] hitting nonexistent API endpoint under /v1/harvester/ gives 500 error and panic backtrace in log

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#6105]
**Describe the bug**
Hit a nonexistent API endpoint directly under `/v1/harvester/` (for example `https://192.168.0.131/v1/harvester/wtf`), and the client will get a 500 internal server error, and the text "EOF" in the response body. Meanwhile, in the logs of the harvester pod, we see:

```
2024/07/02 09:17:48 http: panic serving pipe: runtime error: invalid memory address or nil pointer dereference
goroutine 7890 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x26f2760?, 0x4ef22f0?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/server.(*Server).handle(0xc0008e8930, 0xc000ae7e00, 0x100?)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/server/server.go:154 +0x814
github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/server.(*Server).Handle(0xc000010408?, 0x32400d8?)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/server/server.go:101 +0x17
github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/server/handler.New.(*apiServer).apiHandler.func3({0x32400d8?, 0xc007c9e460?}, 0xc008bd5580?)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/server/handler/apiserver.go:98 +0x7e
net/http.HandlerFunc.ServeHTTP(0xc008bede00?, {0x32400d8?, 0xc007c9e460?}, 0xc008bd5580?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/auth.init.ToMiddleware.func1.1({0x32400d8, 0xc007c9e460}, 0x10?)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/auth/filter.go:172 +0x24c
net/http.HandlerFunc.ServeHTTP(0xc008e4ebd0?, {0x32400d8?, 0xc007c9e460?}, 0x2b13080?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/urlbuilder.RedirectRewrite.func1({0x32400d8?, 0xc007c9e460}, 0xc008bede00)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/apiserver/pkg/urlbuilder/redirect.go:14 +0x152
net/http.HandlerFunc.ServeHTTP(0xc008bedd00?, {0x32400d8?, 0xc007c9e460?}, 0xc009bdb420?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/harvester/harvester/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0009fe900, {0x32400d8, 0xc007c9e460}, 0xc008bedc00)
	/go/src/github.com/harvester/harvester/vendor/github.com/gorilla/mux/mux.go:212 +0x1c5
github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/aggregation.ListenAndServe.ListenAndServe.ToMiddleware.func1.func2({0x32400d8, 0xc007c9e460}, 0x0?)
	/go/src/github.com/harvester/harvester/vendor/github.com/rancher/steve/pkg/auth/filter.go:172 +0x24f
net/http.HandlerFunc.ServeHTTP(0x4f78f20?, {0x32400d8?, 0xc007c9e460?}, 0xc00aaa1b50?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
net/http.serverHandler.ServeHTTP({0xc008e4eba0?}, {0x32400d8?, 0xc007c9e460?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc008e5a750, {0x32514a0, 0xc002605650})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1225
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
```

Note that the harvester pod keeps running just fine - `net/http` appears to have caught and logged the panic, so this isn't critical, it's just weird and ugly.

**To Reproduce**
1. Go to https://192.168.0.131/v1/harvester/wtf (or whatever your management IP address is)
2. Observe that your browser sees a 500 internal server error, and the text "EOF".

**Expected behavior**
A 404 not found error, and no panic/backtrace in the logs.

**Support bundle**
N/A

**Environment**
 - Harvester ISO version: master as at 2024-07-02
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized

**Additional context**
Based on the backtrace, the line that's triggering the panic is:

https://github.com/harvester/harvester/blob/6b79086f42d005c19070b760a877fe27ccb4767a/vendor/github.com/rancher/apiserver/pkg/server/server.go#L154

Given the URL is a path to something that doesn't exist, my money is on `apiOp.Schema` being nil at this point, and that trying to get `apiOp.Schema.ID` is what's causing the panic, which technically makes this a bug in... wait a minute! ~I've just found a PR that will fix this: https://github.com/rancher/apiserver/pull/13~ This should do it: https://github.com/rancher/apiserver/commit/8ad6ac8d69cd5b0605340047c7ea9e675544aac2#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996R155

**Comment by tserong** [comment]
Reopened because #6106 only half-fixes this. The _real_ fix is to update to a newer version of apiserver.

**Comment by Yu-Jack** [comment]
Due to bumping LH v1.7.0-rc2 (https://github.com/harvester/harvester/pull/6173), I also bump the version of apiserver.

**Comment by Yu-Jack** [comment]
> Reopened because #6106 only half-fixes this. The _real_ fix is to update to a newer version of apiserver.

@tserong FYI, I think this one could be closed, I've tested this with latest Harvester ISO and got the 404 status code. You could try that when you're available, thanks.

```
╰─$ curl https://192.168.122.61/v1/harvester/wtf -k -vv
*   Trying 192.168.122.61:443...
* Connected to 192.168.122.61 (192.168.122.61) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: O=dynamic; CN=dynamic
*  start date: Aug 13 04:49:47 2024 GMT
*  expire date: Aug 13 04:54:31 2025 GMT
*  issuer: O=dynamiclistener-org; CN=dynamiclistener-ca@1723524587
*  SSL certificate verify result: self-signed certificate in certificate chain (19), continuing anyway.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://192.168.122.61/v1/harvester/wtf
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: 192.168.122.61]
* [HTTP/2] [1] [:path: /v1/harvester/wtf]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> GET /v1/harvester/wtf HTTP/2
> Host: 192.168.122.61
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/2 404
< date: Mon, 19 Aug 2024 03:38:40 GMT
< content-length: 0
< cache-control: no-cache, no-store, must-revalidate
< x-api-cattle-auth: false
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000; includeSubDomains
<
* Connection #0 to host 192.168.122.61 left intact
```

**Comment by tserong** [comment]
Confirmed, thanks @Yu-Jack !
