### ISSUE TITLE
[BUG] Harvester Terraform Provider 0.6.5 errors when provisioning VM

### ISSUE THREAD

**Issue by git-ival** [harvester/harvester#6647]
**Describe the bug**
Harvester's terraform provider version 0.6.5 errors when applying a module that provisions a VM.

**To Reproduce**
1. Create a terraform module with a `harvester_virtualmachine` resource block
2. Set Harvester provider to version 0.6.5
3. Apply the terraform module
4. Observe an error

**Expected behavior**
The module should be applied successfully and the VM should be provisioned in Harvester.

**Support bundle**
N/A, but terraform provider logs are relevant here and I can provide them via our internal comms as needed.

**Environment**
 - Harvester ISO version: N/A
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): N/A

**Additional context**
`harvester_virtualmachine` block:
```
resource "harvester_virtualmachine" "this" {
  name      = "${var.project_name}-${var.name}"
  namespace = var.namespace
  hostname  = var.name

  tags = merge({
    ssh-user = var.user
    Project  = var.project_name
  }, var.tags)

  cpu    = var.cpu
  memory = "${var.memory}Gi"

  efi         = var.efi
  secure_boot = var.efi ? var.secure_boot : false

  dynamic "network_interface" {
    for_each = data.harvester_network.this
    content {
      name           = network_interface.value.name
      network_name   = network_interface.value.id
      type           = local.networks_map[network_interface.value.name].interface_type
      model          = local.networks_map[network_interface.value.name].interface_model
      wait_for_lease = local.networks_map[network_interface.value.name].wait_for_lease
    }
  }

  dynamic "disk" {
    for_each = local.disks_map
    content {
      name       = disk.value.name
      type       = disk.value.type
      size       = "${disk.value.size}Gi"
      bus        = disk.value.bus
      image      = index(var.disks, disk.value) == 0 ? data.harvester_image.this.id : null
      boot_order = index(var.disks, disk.value) + 1 //boot_order starts at 1, while the index() function is 0-based
    }
  }

  ssh_keys = compact([var.ssh_public_key_id, try(data.harvester_ssh_key.shared[0].id, null)])

  # Default "USB Tablet" config for VNC usage
  input {
    name = "tablet"
    type = "tablet"
    bus  = "usb"
  }

  cloudinit {
    user_data = local.cloud_init_user_data // this is a formatted string of user_data content
  }

  // Allow for more than the default time for VM destruction
  timeouts {
    delete = "15m"
  }
}
```

stderr output:
```
│ Error: Plugin did not respond
│
│   with module.rke2_cluster[2].module.agent_nodes[0].harvester_virtualmachine.this,
│   on ../../modules/harvester_host/main.tf line 1, in resource "harvester_virtualmachine" "this":
│    1: resource "harvester_virtualmachine" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.rke2_cluster[1].module.agent_nodes[0].harvester_virtualmachine.this,
│   on ../../modules/harvester_host/main.tf line 1, in resource "harvester_virtualmachine" "this":
│    1: resource "harvester_virtualmachine" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.rke2_cluster[2].module.server_nodes[0].harvester_virtualmachine.this,
│   on ../../modules/harvester_host/main.tf line 1, in resource "harvester_virtualmachine" "this":
│    1: resource "harvester_virtualmachine" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.rke2_cluster[0].module.server_nodes[0].harvester_virtualmachine.this,
│   on ../../modules/harvester_host/main.tf line 1, in resource "harvester_virtualmachine" "this":
│    1: resource "harvester_virtualmachine" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.rke2_cluster[4].module.server_nodes[0].harvester_virtualmachine.this,
│   on ../../modules/harvester_host/main.tf line 1, in resource "harvester_virtualmachine" "this":
│    1: resource "harvester_virtualmachine" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.rke2_cluster[3].module.server_nodes[0].harvester_virtualmachine.this,
│   on ../../modules/harvester_host/main.tf line 1, in resource "harvester_virtualmachine" "this":
│    1: resource "harvester_virtualmachine" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.rke2_cluster[3].module.agent_nodes[0].harvester_virtualmachine.this,
│   on ../../modules/harvester_host/main.tf line 1, in resource "harvester_virtualmachine" "this":
│    1: resource "harvester_virtualmachine" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.rke2_cluster[1].module.server_nodes[0].harvester_virtualmachine.this,
│   on ../../modules/harvester_host/main.tf line 1, in resource "harvester_virtualmachine" "this":
│    1: resource "harvester_virtualmachine" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-harvester_v0.6.5 plugin:

panic: interface conversion: interface {} is string, not v1.InputType

goroutine 136 [running]:
github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine.(*Constructor).Setup.func14({0x243af20?, 0xc001485530})
        github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine/resource_virtualmachine_constructor.go:296 +0x2bb
github.com/harvester/terraform-provider-harvester/internal/util.ResourceConstruct(0xc000b9d180, {0x2ff9330, 0xc00097ab60})
        github.com/harvester/terraform-provider-harvester/internal/util/constructor.go:98 +0x190
github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine.resourceVirtualMachineCreate({0x3007a40, 0xc0012c0620}, 0xc000b9d180, {0x225bb00, 0xc000c0cb10})
        github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine/resource_virtualmachine.go:48 +0x12d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000b10e00, {0x30079d0, 0xc001192dc0}, 0xc000b9d180, {0x225bb00, 0xc000c0cb10})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:330 +0x10f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b10e00, {0x30079d0, 0xc001192dc0}, 0xc00060bb20, 0xc00097a120, {0x225bb00, 0xc000c0cb10})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:456 +0x81c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00065a120, {0x30079d0, 0xc001192dc0}, 0xc001192e10)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x9ab
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000b244e0, {0x3007998?, 0xc000d36ba0?}, 0xc00060b9d0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0x67
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x2744d60, 0xc000b244e0}, {0x3007998, 0xc000d36ba0}, 0xc000b9ce00, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a5a000, {0x3007998, 0xc000d36b10}, {0x3012860, 0xc00079c000}, 0xc000c3a360, 0xc00086e750, 0x46db700, 0x0)
        google.golang.org/grpc@v1.63.0/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000a5a000, {0x3012860, 0xc00079c000}, 0xc000c3a360)
        google.golang.org/grpc@v1.63.0/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.0/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 31
        google.golang.org/grpc@v1.63.0/server.go:1030 +0x125

Error: The terraform-provider-harvester_v0.6.5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by bk201** [comment]
cc @FrankYang0529 @m-ildefons

**Comment by m-ildefons** [comment]
The error happens due to the lack of an appropriate type cast when parsing the input device block:
```
  # Default "USB Tablet" config for VNC usage
  input {
    name = "tablet"
    type = "tablet"
    bus  = "usb"
  }
```
The Terraform code here is correct, our provider has indeed a bug. A quick workaround would be to remove the input block and edit the resulting VM once it has been created via the web UI.

**Comment by w13915984028** [comment]
Move this issue to v1.5.0 for further planning.

**Comment by bk201** [comment]
cc @m-ildefons to check the issue status

**Comment by khushboo-rancher** [comment]
@irishgordo We can update e2e test with the terraform and run the related test case.

**Comment by irishgordo** [comment]
Looks good 👍 😄 
Thanks for the fix @m-ildefons 

On loadout:
- Harvester: v1.5.0-rc1, single node bare-metal HP DL 360 Gen 9
- Harvester Terraform Provider: v0.6.6

Test Terraform:
```terraform
resource "harvester_image" "minio-img" {
  name         = var.MINIOSERVER_CLOUD_IMG_NAME
  namespace    = var.MINIOSERVER_NAMESPACE_DESIRED
  display_name = var.MINIOSERVER_CLOUD_IMG_DISPLAYNAME
  source_type  = "download"
  url          = var.MINIOSERVER_CLOUD_IMG_URL
}

resource "harvester_cloudinit_secret" "cloud-config-minio" {
  name      = "cloud-config-minio"
  namespace = var.MINIOSERVER_NAMESPACE_DESIRED
  user_data = <<-EOF
      #cloud-config
      password: ${var.MINIOSERVER_VM_PW}
      chpasswd:
        expire: false
      ssh_pwauth: true
      package_update: true
      packages:
        - qemu-guest-agent
        - apt-transport-https
        - neovim
        - wget
        - ca-certificates
        - python3
        - python3-pip
        - jq
        - curl
        - gnupg-agent
        - gnupg
        - lsb-release
        - htop
        - parted
        - fdisk
        - gnupg2
        - neovim
        - software-properties-common
        - coreutils
        - sshpass
        - tmux
        - net-tools
        - unzip
      runcmd:
        - - systemctl
          - enable
          - --now
          - qemu-guest-agent.service
    EOF

  # network_data = <<-EOF
  #     network:
  #       version: 2
  #       ethernets:
  #         enp1s0:
  #           dhcp4: true
  #           nameservers:
  #             addresses: [1.1.1.1]
  # EOF

}
#  harvester_network.mgmt-vlan-minio
resource "harvester_virtualmachine" "minio-vm" {
  depends_on = [
    harvester_cloudinit_secret.cloud-config-minio, harvester_image.minio-img
  ]

  timeouts {
    create = "10m"
    delete = "10m"
  }

  name                 = var.MINIOSERVER_NAME
  namespace            = var.MINIOSERVER_NAMESPACE_DESIRED
  restart_after_update = true

  description = "MINIO VM for Integrations of Harvester"
  tags = {
    ssh-user                      = "ubuntu"
    ssh-user-pw                   = var.MINIOSERVER_VM_PW
    minio_config_disk_size        = var.MINIOSERVER_CONFIG_DISK_SIZE_IN_G
    minio_config_disk_device      = var.MINIOSERVER_CONFIG_DISK_DEVICE
    minio_config_web_console_port = var.MINIOSERVER_CONFIG_WEB_CONSOLE_PORT
    minio_config_api_port         = var.MINIOSERVER_CONFIG_API_PORT
    minio_config_https_enabled    = var.MINIOSERVER_CONFIG_HTTPS_ENABLED
    minio_config_user             = var.MINIOSERVER_CONFIG_USER
    minio_config_password         = var.MINIOSERVER_CONFIG_PASSWORD
    minio_config_region           = var.MINIOSERVER_CONFIG_REGION
    minio_config_bucket_name      = var.MINIOSERVER_CONFIG_BUCKET_NAME
    minio_config_access_key       = var.MINIOSERVER_CONFIG_ACCESS_KEY
    minio_config_secret_key       = var.MINIOSERVER_CONFIG_SECRET_KEY
  }

  connection {
    type     = "ssh"
    host     = self.network_interface[0].ip_address
    user     = "ubuntu"
    password = var.MINIOSERVER_VM_PW
  }

  # IMPORTANT: We need to wait for cloud-init on Harvester VMs to complete before running Ansible
  # Additionally, cloud-init shouldn't take too long, ideally most configuration should be done in Ansible for better levels of control
  provisioner "remote-exec" {
    inline = [
      "echo 'Waiting for cloud-init to complete...'",
      "cloud-init status --wait > /dev/null",
      "echo 'Completed cloud-init!'",
    ]
  }

  cpu    = var.MINIOSERVER_DESIRED_CPU
  memory = var.MINIOSERVER_DESIRED_MEM

  # Default "USB Tablet" config for VNC usage
  input {
    name = "tablet"
    type = "tablet"
    bus  = "usb"
  }

  efi         = true
  secure_boot = false

  run_strategy = "RerunOnFailure"
  hostname     = var.MINIOSERVER_NAME
  machine_type = "q35"

  network_interface {
    name           = "nic-1"
    wait_for_lease = true
    model          = "virtio"
    type           = "bridge"
    network_name   = "vlan2011"
  }

  disk {
    name       = "rootdisk"
    type       = "disk"
    size       = var.MINIOSERVER_DISK_SIZE
    bus        = "virtio"
    boot_order = 1

    image       = harvester_image.minio-img.id
    auto_delete = true
  }


  disk {
    name = var.MINIOSERVER_STORAGE_DISK_NAME
    type = "disk"
    size = var.MINIOSERVER_STORAGE_DISK_SIZE
    bus  = "virtio"

    auto_delete = true
  }

  cloudinit {
    user_data_secret_name = harvester_cloudinit_secret.cloud-config-minio.name
    #network_data_secret_name = harvester_cloudinit_secret.cloud-config-minio.name
  }

}
```

A small takeway, is that it's now very important for resources built with the Terraform Harvester Provider to incorporate:
```terraform
  timeouts {
    create = ""
    delete = ""
  }
```
Depending on how long it might take before that resource can become active.

![Image](https://github.com/user-attachments/assets/72c92656-2301-42d4-b8d2-87ab454f6129)
![Image](https://github.com/user-attachments/assets/9a6f4e73-6fde-4a58-86aa-ed03536e5cb3)

I'll go ahead and close this out -as the automation to modify the fixture is currently drafted as well.
