### ISSUE TITLE
[BUG] virt-controller crashLoopBackOff

### ISSUE THREAD

**Issue by SnelsSM** [harvester/harvester#6749]
**Describe the bug**
Harvester CSI (?) is incorrectly mounting volumes in Kubernetes clusters. Volumes from one cluster are being mounted to virtual machines in a different cluster. This causes the virt-controller to crash and prevents virtual machines from starting, being created, or stopping. 

Log from virt-controller
```
{"component":"virt-controller","kind":"VirtualMachine","level":"error","msg":"Reconciling the VirtualMachine failed.","name":"mops-branch-1-master-vrq5f-9f7mw","namespace":"mops-local","pos":"vm.go:382","reason":"Error encountered when trying to update vm according to add volume and/or memory dump requests: admission webhook \"validator.harvesterhci.io\" denied the request: the volume pvc-d9e73d01-ad0d-4d67-a581-0049d2431dbf is already used by VM mops-local/mops-smia-demo-master-nf789-5dqz5","timestamp":"2024-10-10T04:51:51.677037Z","uid":"761aa913-12f8-4739-8dd4-9dd626daa1f3"}
E1010 04:51:51.677279       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1605 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x563c33e385a0?, 0x563c351d3df0})
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2b?})
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x563c33e385a0?, 0x563c351d3df0?})
	/usr/lib64/go/1.21/src/runtime/panic.go:914 +0x21f
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).isVirtualMachineStatusDataVolumeError(0x0?, 0xc001e61200, 0x0?)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:2432 +0x50
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).setPrintableStatus(0xc00054a1e0, 0xc001e61200, 0xc003ba3ae0?)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:2298 +0x4c2
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).updateStatus(0xc00054a1e0, 0xc00211f400, 0xc003ba3ae0, {0x563c34142f60, 0xc0017d1540}, 0x2?)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:2245 +0x329
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).execute(0xc00054a1e0, {0xc004215110, 0x2b})
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:385 +0xe3b
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).Execute(0xc00054a1e0)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:280 +0x1fd
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).runWorker(...)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:260
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x563c34133248, 0xc00718c030}, 0x1, 0xc003538a80)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92 +0x1e
created by kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).Run in goroutine 1403
	/home/abuild/rpmbuild/BUILD/kubevirt-1.1.1/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:252 +0x3c6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2d8 pc=0x563c334a4f50]
```
mops-branch-1 and mops-smia-demo - two different clusters.

The same issue occurs within a single cluster. Virtual machines cannot restart/start/stop because the volume is mounted to a different VM. Why it's mounted there and why it won't unmount is a mystery to me.

**To Reproduce**
I don't have a reproducible scenario. This is a fresh installation of Harvester 1.3.2 + Rancher 2.9.2.
I simply created several Kubernetes clusters, with Harvester acting as the cloud provider in each. 
Each of these clusters utilizes volumes via Harvester CSI. After virtual machines are stopped for some reason (e.g., OOM Killer), this problem occurs. This isn't the first time this has happened.

**Expected behavior**
1. Volumes should not be mounted outside their intended target.
2. The virt-controller should not crash with an "invalid memory address or nil pointer dereference" error, as this completely disrupts the management of all virtual machines in Harvester HCI. 

**Environment**
 - Harvester ISO version: 1.3.2
 - Rancher: 2.9.2
 - Underlying Infrastructure: ASUS/Gigabyte + AMD EPYC

**Comment by Vicente-Cheng** [comment]
We have encountered this issue serval times. Re-opened.

**Comment by Vicente-Cheng** [comment]
cc @ibrokethecloud, @bk201, @ihcsim

**Comment by SnelsSM** [comment]
Yes... It is not possible to use the downstream longhorn normally through harvester-csi.
Simply because the volumes in harvester connect to the wrong virtual machines...

Now we have to use ceph-rbd-csi to solve this problem.

**Comment by ihcsim** [comment]
@SnelsSM Re: the wrong mount target, does https://github.com/harvester/harvester/issues/6981 sound similar to what you saw? It's now fixed in Harvester 1.4.0.

Re: the virt-controller panic, I haven't been able to reproduce it but I suspect the error returned by the validating webhook triggered an unexpected issue in the [kubevirt 1.1.1 code path](https://github.com/kubevirt/kubevirt/blob/689c0e66cc6893f311dd648ff32e247203b6c96a/pkg/virt-controller/watch/vm.go#L2845-L2854), where the `err` check was omitted and an empty `vm` got passed to the subsequent update status call. That triggered a panic [here](https://github.com/kubevirt/kubevirt/blob/689c0e66cc6893f311dd648ff32e247203b6c96a/pkg/virt-controller/watch/vm.go#L2432). From what I see, this was fixed in https://github.com/kubevirt/kubevirt/commit/38d062bd57b924e60ffec724f6484b7995a47801, and included in kubevirt 1.2, which Harvester 1.4.0 uses. 

Try upgrade to Harvester 1.4.0. If upgrade is not possible, the workaround for 1.3.2 is to remove the conflicting VM that tried to mount the already-attached PVC. Based on your description, sounds like the `mops-branch-1-master-vrq5f-9f7mw` VM is not supposed to mount the `pvc-d9e73d01-ad0d-4d67-a581-0049d2431dbf` volume because it belongs to another cluster?

**Comment by ihcsim** [comment]
@SnelsSM Does any of your VM uses kubevirt dataVolume? Can you confirm by checking the output of `kubectl get vm -A -o yaml`? Thanks.

**Comment by AdamJSoftware** [comment]
I upgraded harvester to 1.4.0 however I am still seeing this issue. I'll try deleting and recreating the VM's to see if that prevents the issue from occurring

**Comment by ibrokethecloud** [comment]
is it possible for you to please share a support bundle from this cluster which have VM's in this state?

**Comment by innobead** [comment]
This was accidentally closed in the sprint for 1.5.0. Moving to the next release instead. 

cc @harvester/release

**Comment by ihcsim** [comment]
I am closing this issue for now since we haven't been able to reproduce it since upgrading to kubevirt 1.2. Feel free to re-open this issue if this happens again in Harvester v1.4.0+, with support bundles. Thanks.
