### ISSUE TITLE
[BUG] In monitoring addon, one of the node exporter keep crashing because of some content in /proc/mdstat

### ISSUE THREAD

**Issue by ER-EPR** [harvester/harvester#7095]
**Describe the bug**

One of the node exporter keeps crashing, when processing mdstat, the pod log show `panic: runtime error: index out of range [0] with length 0`.
![image](https://github.com/user-attachments/assets/5166e0af-a838-48a1-aee4-3753015486ff)
I don't know if this is a Prometheus bug or the version in harvester addon lack some of the text processing capabilities updates.
So I create a issue also in prometheus repo.
https://github.com/prometheus/node_exporter/issues/3198
The content of /proc/mdstat is
```
Personalities : [raid6] [raid5] [raid4]
md125 : inactive sdc1[29](S) sdb1[27](S) sde1[28](S) sda1[26](S) sdd1[30](S)
      41937920 blocks super 1.2

md126 : active raid5 super 1.2 level 5, 64k chunk, algorithm 2 [4/0] [____]

md127 : inactive sdc2[28](S) sdb2[30](S) sda2[27](S) sdd2[29](S) sde2[26](S)
      10480640 blocks super 1.2

unused devices: <none>
```
**To Reproduce**
1. Write a kernel module to create a file /proc/mdstat with content same as above. (although mine is created by the system because some raid disks are in the server, and I am not familiar with how to write a kernel module, so I can't provide the exact code, but it is certainly possable.)
2. enable monitoring addon
3. the node exporter on this node crashed

**Expected behavior**

pod running
**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell R730xd

**Additional context**

**Comment by starbops** [comment]
@ER-EPR If possible, could you attach the support bundle please? Thank you. cc @w13915984028

**Comment by ER-EPR** [comment]
I already have a work around, add an command line Exra Arg `--no-collector.mdadm` to the node exporter Daemon Set. 
Which according to Prometheus Doc will exclude the /proc/mdstat file from being processed. https://github.com/prometheus/node_exporter/blob/master/README.md#collectors
@starbops I think there is no need to analyze the support bundle. Because I already fixed it, I would have to roll back and trigger the crash to acquire the support bundle, but it is not necessary now. It is the content of /proc/mdstat I provided above which cause the crash, it is quite clear. 
So I think there is a way to reproduce this error, just create /proc/mdstat with same content would trigger the crash. Although a  custom kernel module is needed to do that, and I don't know how to write it.
![48057a0e5c733ddd4e34606b296601c](https://github.com/user-attachments/assets/c5facacb-dfe9-4d9d-8360-07b93dc7dcb5)

**Comment by w13915984028** [comment]
The issue has been fixed by upstream https://github.com/prometheus/procfs/commit/b9b5ad9b6d5a3ba720f13d9e0ff0ff9eb8ad3a3d#diff-1661c40d89115402230dda8d0195c034b40fb46a3d60d05b9baa649b37277c8aL170

I just reproduced it via following code:

```
go122 run main.go 
0 Personalities : [raid6] [raid5] [raid4]
1 md125 : inactive sdc1[29](S) sdb1[27](S) sde1[28](S) sda1[26](S) sdd1[30](S)
the output 0 5 0 0 0 41937920 md125 inactive2       41937920 blocks super 1.2
3 
4 md126 : active raid5 super 1.2 level 5, 64k chunk, algorithm 2 [4/0] [____]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.evalStatusLine({0xc000138096, 0x4b}, {0xc0001380e2, 0x0})
	/home/jianwang/Documents/other/main.go:88 +0x505
main.test_mdoutput({0xc000138000?, 0xc000136000?})
	/home/jianwang/Documents/other/main.go:61 +0x2d7
main.test_with_input()
```

If you are interested, copy the main.go and input.txt

https://github.com/w13915984028/harvester-develop-summary/blob/15efd407a258738ac4eb479696230047cd049d13/test-code/reproduce-gh-7095/main.go#L172

```
// run `go run main.go` to reproduce the issue
// run `go run main.go 1` to validate the fix solves the issue
```

We will check the `rancher-monitoring` chart and bump properly. Thanks @ER-EPR

**Comment by w13915984028** [comment]
The Harvester v1.3.2 was still with prometheus-node-exporter `tag: v1.3.1`

https://github.com/rancher/charts/blob/e9ce40b20cbc993d1d52764223f1c55820c59290/charts/rancher-monitoring/103.1.1%2Bup45.31.1/charts/prometheus-node-exporter/values.yaml#L9

From `104.1.0+Up57.0.3` with prometheus-node-exporter [tag v1.7.0](https://github.com/prometheus/node_exporter/releases/tag/v1.7.0) this bug is fixed.

https://github.com/rancher/charts/blob/e9ce40b20cbc993d1d52764223f1c55820c59290/charts/rancher-monitoring/104.1.0%2Bup57.0.3/charts/prometheus-node-exporter/values.yaml#L9

The bump will be done on Harvester v1.4.1/v1.5.0.

**Comment by w13915984028** [comment]
FYI: Another **workaround** is to set `prometheus-node-exporter` with image tag `v1.7.0`, it fixed this issue.

**Comment by ER-EPR** [comment]
OK, it's running now, I'll wait for the v1.4.1.
