### ISSUE TITLE
[BUG] Terraform provider crashes with panic if disk type is "cd-rom" and disk size is not set

### ISSUE THREAD

**Issue by linguini-dev** [harvester/harvester#7139]
**Describe the bug**
Creating a virtualmachine resource with a disk of type "cd-rom" but without specifying the size crashes the terraform provider.

**Steps To Reproduce**
1. Try to create a `harvester_virtualmachine` resource with the following disk configuration:
```
  disk {
    name           = "main"
    type           = "disk"
    bus            = "virtio"
    size           = "80Gi"
  }
  
  disk {
    name           = "cdrom-disk"
    type           = "cd-rom"
    bus            = "sata"
    boot_order = 1
    image = data.harvester_image.myimage.id
  }
```

**Expected behavior**
The documentation states that only a `name` is required for the `disk` object. https://github.com/harvester/terraform-provider-harvester/blob/master/docs/resources/virtualmachine.md#nested-schema-for-disk However this is not the case, `size` is also required for both `disk` and `cd-rom` types.

1. The terraform provider should give a proper error and not throw a panic.
2. If `size` is indeed a required parameter, it should be reflected in the documentation.

**Environment**
 - Harvester version: v2.8.6
 - Terraform Harvester provider version: 0.6.6
 - OpenTofu version: v1.7.1

**Additional context**
The stack trace:
```
panic: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

goroutine 133 [running]:
k8s.io/apimachinery/pkg/api/resource.MustParse({0x0, 0x0})
	k8s.io/apimachinery@v0.31.1/pkg/api/resource/quantity.go:139 +0x173
github.com/harvester/harvester/pkg/builder.(*VMBuilder).PVCVolume(0xc000216f80, {0xc000e81510, 0xa}, {0x0, 0x0}, {0x0?, 0xc0000da2e0?}, 0x0, 0xc000d37a40?)
	github.com/harvester/harvester@v1.3.2/pkg/builder/disk.go:186 +0x365
github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine.(*Constructor).Setup.func12({0x249eba0?, 0xc000c98930})
	github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine/resource_virtualmachine_constructor.go:259 +0xeab
github.com/harvester/terraform-provider-harvester/internal/util.ResourceConstruct(0xc000d2ea00, {0x3073690, 0xc0001527a0})
	github.com/harvester/terraform-provider-harvester/internal/util/constructor.go:98 +0x190
github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine.resourceVirtualMachineCreate({0x3081d40, 0xc000d37a40}, 0xc000d2ea00, {0x22ba5e0, 0xc000cd8720})
	github.com/harvester/terraform-provider-harvester/internal/provider/virtualmachine/resource_virtualmachine.go:47 +0x12d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000b9e0e0, {0x3081cd0, 0xc0004a47d0}, 0xc000d2ea00, {0x22ba5e0, 0xc000cd8720})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:330 +0x10f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b9e0e0, {0x3081cd0, 0xc0004a47d0}, 0xc000d373b0, 0xc0006417e0, {0x22ba5e0, 0xc000cd8720})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:456 +0x81c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00082df08, {0x3081cd0, 0xc0004a47d0}, 0xc0004a4820)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x9ab
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0008c6b80, {0x3081c98?, 0xc000bf2300?}, 0xc000d37180)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0x67
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x27b1ea0, 0xc0008c6b80}, {0x3081c98, 0xc000bf2300}, 0xc000cd7e00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000771400, {0x3081c98, 0xc000bf2270}, {0x308d060, 0xc0008cba00}, 0xc000bee6c0, 0xc0009dda40, 0x478d5c0, 0x0)
	google.golang.org/grpc@v1.67.0/server.go:1394 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc000771400, {0x308d060, 0xc0008cba00}, 0xc000bee6c0)
	google.golang.org/grpc@v1.67.0/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.67.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 114
	google.golang.org/grpc@v1.67.0/server.go:1040 +0x125

Error: The terraform-provider-harvester_v0.6.6 plugin crashed!
```

**Comment by innobead** [comment]
cc @m-ildefons

**Comment by m-ildefons** [comment]
Hi @linguini-dev ,

The crash is indeed a bug. However the `size` parameter of the `disk` subresource is not in all cases mandatory. For example, when using the `existing_volume_name` parameter, or the `container_image_name`, the `size` parameter will be ignored.
Regardless, the correct behavior would be to fall back to a default value, if the size isn't given at all, and to error out gracefully if the size isn't parseable.

**Comment by linguini-dev** [comment]
> Hi @linguini-dev ,
> 
> The crash is indeed a bug. However the `size` parameter of the `disk` subresource is not in all cases mandatory. For example, when using the `existing_volume_name` parameter, or the `container_image_name`, the `size` parameter will be ignored. Regardless, the correct behavior would be to fall back to a default value, if the size isn't given at all, and to error out gracefully if the size isn't parseable.

Sounds good to me :)

**Comment by innobead** [comment]
@bk201 should we track this in 1.5.0? This should be independent from specific milestones.

**Comment by irishgordo** [comment]
@m-ildefons in general this looks good 😄 👍 

I'm closing this out and will track these other issues separately here:

- https://github.com/harvester/harvester/issues/7853
- https://github.com/harvester/harvester/issues/7852
