### ISSUE TITLE
[BUG] mutations.js:42 TypeError: Cannot read properties of undefined (reading 'volumeAttributes')

### ISSUE THREAD

**Issue by goldyfruit** [harvester/harvester#7150]
**Describe the bug**

I removed a `volumesnapshotstorageclass` _(not the Longhorn ones)_ and now I can't list the volumes in the UI.

```
mutations.js:42 TypeError: Cannot read properties of undefined (reading 'volumeAttributes')
    at get isEncrypted (persistentvolumeclaim.js:232:37)
    at fn (harvesterhci.io.volume.vue:1:844)
    at o (vue.min.js:11:16260)
    at a.lt [as _t] (vue.min.js:11:13511)
    at fn (ResourceTable.vue:1:1740)
    at o (vue.min.js:11:16260)
    at a.lt [as _t] (vue.min.js:11:13511)
    at index.vue:8:209
    at a.ut [as _l] (vue.min.js:11:13080)
    at index.vue:8:164
```

![image](https://github.com/user-attachments/assets/b5195531-36c9-49b5-bcdb-592a938a175a)

**Expected behavior**

List the volumes without error.

**Support bundle**

Already provided to the team on Slack.

**Environment**
 - Harvester ISO version: 1.4.0
 - Underlying Infrastructure: Dell R720

**Comment by bcdurden** [comment]
I am also seeing this issue but it is crashing elsewhere.
```console
console.js:31 Cannot read properties of undefined (reading 'volumeAttributes')
this.$el.querySelector is not a function
e.forEach.console.<computed>	@	console.js:31
```

Dell R630s on Harvester 1.4.  I have read that Kasten may be to blame as removal of it fixed the issue for someone else. I cannot do this as I use Kasten for backups of my VMs and services on Harvester.

I suspect this will make it easy to reproduce (just install Kasten, I am using version 7.0.5).

**Comment by a110605** [comment]
~~Is there any clear reproduce steps how to trigger this error ?~~

Per disucssed with @Vicente-Cheng, he will help find out the clear reproduce steps that missing `this.spec.csi`. 

PR is pending for review.

**Comment by bcdurden** [comment]
For error reproduction, I suspect it is due to some kind of
annotation/label error. Kasten is what I use for backups in Harvester and I
suspect that the volumes it creates (storage classes with a block volume
tag) are causing the problem. Or perhaps the RWX storage class I created
manually in 1.3.2 (livemigration disabled). See here for details on Kasten:
https://veeamkasten.dev/harvester

**Comment by tserong** [comment]
I tried experimentally just installing Kasten and wasn't able to reproduce the problem. I'm not sure exactly what operations I'd need to _do_ with Kasten to hit it, but after some further discussion we've determined that this error will occur if there's a PVC/PV pair (so Harvester wants to list it under "Volumes" because there's a PVC), but where the related PV _doesn't_ have `.spec.csi`, i.e. is some different type, like maybe NFS or iSCSI.

I faked up a reproducer as follows:

```
# cat fake-pv-local.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fake-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: fake-pvc
    namespace: default
  volumeMode: Block
  local:
    path: /tmp/foo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - fake-node-name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fake-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Block
  volumeName: fake-pv

# kubectl create -f fake-pv-local.yaml
```

@goldyfruit, @bcdurden, in your cases where you're hitting the problem for real, please trying running this little thing:

```
for volumeName in $(kubectl get pvc -o jsonpath='{..spec.volumeName}') ; do [ -z "$(kubectl get pv/$volumeName -o jsonpath='{..spec.csi}')" ] && echo $volumeName ; done
```

That should print out the name of any PVs, which have a matching PVC, but _don't_ specify `.spec.csi`. Assuming that works, then try `kubectl describe pv/WHATEVER_WAS_PRINTED_ABOVE` and we'll have (hopefully!) found the culprit.

**Comment by lanfon72** [comment]
Verified this bug not been fixed yet, move back to implement.

![Image](https://github.com/user-attachments/assets/2c24d08d-d05d-4abc-88fd-07c108bb9108)

Test Information
----
* Environment: **baremetals DL360G9 4 nodes**
* Harvester Version: **v1.5.0-dev-20250203**
* **ui-source** Option: **External**

### Verify Steps
1. Install Harvester with any nodes
2. Access embedded Rancher (Enable developer features in preference)
3. Navigate to __Storage/PersistentVolumes__ then create PV using the yaml as below
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fake-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: fake-pvc
    namespace: default
  volumeMode: Block
  local:
    path: /tmp/foo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - fake-node-name
```
4. Navigate to __Storage/Volumes__ page, create new Volume **fake-pvc** using existing PV `fake-pv` with `Access Modes: Many Nodes Read-Write`
5. Access Harvester dashboard then navigate to **Volumes** page
6. The page should work normally and the volume `fake-pvc` should displayed in the list

**Comment by a110605** [comment]
Sorry forget to cherry-pick to `release-harvester-v1.5` branch.
Done in https://github.com/harvester/harvester-ui-extension/pull/123.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.5-7e12eb95-head**
* **ui-source** Option: **Auto**

### Verify Steps
- Same as https://github.com/harvester/harvester/issues/7150#issuecomment-2648995423
