### ISSUE TITLE
[BUG] Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#838]
**Describe the bug**

```bash
❯ kubectl get po
NAME                                                   READY   STATUS             RESTARTS   AGE
cdi-apiserver-54d588847-jhtwd                          1/1     Running            1          149m
cdi-deployment-65fbdb7588-wf9c7                        1/1     Running            1          149m
cdi-operator-74dc8595f5-dbqhz                          1/1     Running            1          150m
cdi-uploadproxy-544fcccc78-96drq                       1/1     Running            1          149m
harvester-9f85f8dd6-52n9t                              0/1     Pending            0          150m
harvester-9f85f8dd6-n27jt                              0/1     Pending            0          150m
harvester-9f85f8dd6-vmpjt                              0/1     CrashLoopBackOff   6          150m
harvester-network-controller-6k4mn                     1/1     Running            1          150m
harvester-network-controller-manager-87d66b4b6-sq8wt   1/1     Running            1          150m
harvester-network-controller-manager-87d66b4b6-zbg8m   1/1     Running            1          150m
virt-api-5fbd56d6c9-4xp65                              1/1     Running            1          148m
virt-api-5fbd56d6c9-8nwpl                              1/1     Running            1          148m
virt-controller-75c7bbb964-fg2ch                       1/1     Running            1          147m
virt-controller-75c7bbb964-t7rgl                       1/1     Running            1          147m
virt-handler-kc7mv                                     1/1     Running            1          147m
virt-operator-7dd868747b-fw62v                         1/1     Running            1          150m
```
```bash
E0508 07:26:26.734594       7 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1305 [running]:
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x22bca40, 0x4326e30)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x92
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x22bca40, 0x4326e30)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).saveInK8s(0xc000cb60e0, 0xc0020c5140, 0xc001196b98, 0xc00140e620, 0xc000f7ac60)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:144 +0xae
github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).Update(0xc000cb60e0, 0xc0020c5140, 0x0, 0x0)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:170 +0xb5
github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).init.func1(0xc0020ccc80, 0x18, 0xc0020c5140, 0xc0020e8d01, 0xc001196b48, 0x403744)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:83 +0x95
github.com/harvester/harvester/vendor/github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1(0xc0020ccc80, 0x18, 0x2a7c8a0, 0xc0020c5140, 0xc001a2e400, 0xc001196b78, 0xc001196b78, 0x412e42)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/wrangler/pkg/generated/controllers/core/v1/secret.go:102 +0x65
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc001a2e030, 0xc0020ccc80, 0x18, 0x2a7c8a0, 0xc0020c5140, 0xc001196be0, 0x40908b, 0x27e1798, 0x243bda0)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc001376420, 0xc0020ccc80, 0x18, 0x2a7c8a0, 0xc0020c5140, 0x42e301, 0x0)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000a20580, 0xc0020ccc80, 0x18, 0xc001cee4b0, 0xc001196d40)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:210 +0xd1
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000a20580, 0x219bec0, 0xc001a2e410, 0x0, 0x0)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:192 +0xf0
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000a20580, 0x798f01)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:169 +0x51
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000a20580)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:158 +0x2b
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001c7b190)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001c7b190, 0x2a47860, 0xc001841170, 0x1, 0xc0000ba0c0)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001c7b190, 0x3b9aca00, 0x0, 0xc001b9a601, 0xc0000ba0c0)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc001c7b190, 0x3b9aca00, 0xc0000ba0c0)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:129 +0x35e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1d8963e]

goroutine 1305 [running]:
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x22bca40, 0x4326e30)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).saveInK8s(0xc000cb60e0, 0xc0020c5140, 0xc001196b98, 0xc00140e620, 0xc000f7ac60)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:144 +0xae
github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).Update(0xc000cb60e0, 0xc0020c5140, 0x0, 0x0)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:170 +0xb5
github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes.(*storage).init.func1(0xc0020ccc80, 0x18, 0xc0020c5140, 0xc0020e8d01, 0xc001196b48, 0x403744)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go:83 +0x95
github.com/harvester/harvester/vendor/github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1(0xc0020ccc80, 0x18, 0x2a7c8a0, 0xc0020c5140, 0xc001a2e400, 0xc001196b78, 0xc001196b78, 0x412e42)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/wrangler/pkg/generated/controllers/core/v1/secret.go:102 +0x65
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc001a2e030, 0xc0020ccc80, 0x18, 0x2a7c8a0, 0xc0020c5140, 0xc001196be0, 0x40908b, 0x27e1798, 0x243bda0)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc001376420, 0xc0020ccc80, 0x18, 0x2a7c8a0, 0xc0020c5140, 0x42e301, 0x0)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/sharedhandler.go:65 +0x150
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000a20580, 0xc0020ccc80, 0x18, 0xc001cee4b0, 0xc001196d40)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:210 +0xd1
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000a20580, 0x219bec0, 0xc001a2e410, 0x0, 0x0)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:192 +0xf0
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000a20580, 0x798f01)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:169 +0x51
github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc000a20580)
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:158 +0x2b
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001c7b190)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001c7b190, 0x2a47860, 0xc001841170, 0x1, 0xc0000ba0c0)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001c7b190, 0x3b9aca00, 0x0, 0xc001b9a601, 0xc0000ba0c0)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xaa
github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc001c7b190, 0x3b9aca00, 0xc0000ba0c0)
        /go/src/github.com/harvester/harvester/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/src/github.com/harvester/harvester/vendor/github.com/rancher/lasso/pkg/controller/controller.go:129 +0x35e
```

**To Reproduce**
1. restart harvester repeatedly

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
```bash
❯ kubectl get no -owide
NAME     STATUS   ROLES                  AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
master   Ready    control-plane,master   28h   v1.21.0   192.168.1.213   <none>        CentOS Linux 7 (Core)   5.4.117-1.el7.elrepo.x86_64   docker://20.10.6
```

**Comment by futuretea** [comment]
workaround:

```diff
diff --git a/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go b/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go
index 4216eb19..86418a47 100644
--- a/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go
+++ b/vendor/github.com/rancher/dynamiclistener/storage/kubernetes/controller.go
@@ -126,11 +126,11 @@ func (s *storage) targetSecret() (*v1.Secret, error) {
 }

 func (s *storage) saveInK8s(secret *v1.Secret) (*v1.Secret, error) {
-       if s.secrets == nil {
+       if s.secrets == nil || s.tls == nil {
                return secret, nil
        }

-       if existing, err := s.storage.Get(); err == nil && s.tls != nil {
+       if existing, err := s.storage.Get(); err == nil {
                if newSecret, updated, err := s.tls.Merge(existing, secret); err == nil && updated {
                        secret = newSecret
                }
```

**Comment by weihanglo** [comment]
Maybe this helps
https://github.com/rancher/dynamiclistener/pull/41

**Comment by futuretea** [comment]
## To test:
1. restart harvester repeatly by (kubectl delete po harvester-xxxxxx)
2. check if harvester pod will  panic

**Comment by ldevulder** [comment]
I've tested on version `master-7b0da5d1-head` and I was not able to reproduce the issue (I've tested more than 10 `kubectl delete` commands on different pods).

So the issue seems to be fixed, issue can be closed.
