### ISSUE TITLE
[Bug] etcd panic after power off

### ISSUE THREAD

**Issue by insbire** [harvester/harvester#996]
We are trying to build a harvester server for test envorienment. 

1. The installation is problemlos, up and running.
2. Plug out LAN cable, turn on the server. Of course unavailable
3. Plug in the LAN cable, restart server. The DHCP not working, still unavailable

Harvester management URL:  Unavailable
Current status:                         Setting up Harvester

I need to config harvester manual. In the doc, https://docs.harvesterhci.io/v0.2/install/harvester-configuration/, cant find any infos about the location of Harvester configuration file. Can U pls descript the Harvester manual configuration more specific? thx!

**Comment by yaocw2020** [comment]
If DHCP doesn't work, you should configure a static IP while installation.

**Comment by insbire** [comment]
Yeah, that's why i wanna config harvester manual AFTER installation.

**Comment by yaocw2020** [comment]
> Yeah, that's why i wanna config harvester manual AFTER installation.

You can not config the IP after installation. I recommend you to reinstall the Harvester and configure an static IP while installation. Related document: https://docs.harvesterhci.io/v0.2/install/iso-install/
![image](https://user-images.githubusercontent.com/7421463/124413108-962dc100-dd82-11eb-93d3-a005654102ec.png)

**Comment by yaocw2020** [comment]
[k3s-service.log](https://onedrive.live.com/?authkey=%21AEshTRhzH5tpFcM&cid=5ABEA84C428ECABF&id=5ABEA84C428ECABF%21852&parId=5ABEA84C428ECABF%21770&o=OneUp)

```
goroutine 290 [running]:
github.com/rancher/k3s/vendor/go.etcd.io/bbolt.(*DB).freepages.func2(0xc0017e8840)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/bbolt/db.go:1003 +0xe9
created by github.com/rancher/k3s/vendor/go.etcd.io/bbolt.(*DB).freepages
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/bbolt/db.go:1001 +0x1cd
time="2021-07-05T00:02:47.310814618Z" level=info msg="Found ip 192.168.10.8 from iface eth3"
time="2021-07-05T00:02:47.310910092Z" level=info msg="Starting k3s v1.20.4+k3s1 (838a906a)"
time="2021-07-05T00:02:47.311174632Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
{"level":"info","ts":"2021-07-05T00:02:47.347Z","caller":"embed/etcd.go:117","msg":"configuring peer listeners","listen-peer-urls":["https://192.168.10.8:2380"]}
{"level":"info","ts":"2021-07-05T00:02:47.347Z","caller":"embed/etcd.go:468","msg":"starting with peer TLS","tls-info":"cert = /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt, key = /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key, trusted-ca = /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt, client-cert-auth = true, crl-file = ","cipher-suites":[]}
{"level":"info","ts":"2021-07-05T00:02:47.348Z","caller":"embed/etcd.go:127","msg":"configuring client listeners","listen-client-urls":["https://127.0.0.1:2379","https://192.168.10.8:2379"]}
{"level":"info","ts":"2021-07-05T00:02:47.348Z","caller":"embed/etcd.go:302","msg":"starting an etcd server","etcd-version":"3.4.13","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.15.8","go-os":"linux","go-arch":"amd64","max-cpu-set":48,"max-cpu-available":48,"member-initialized":true,"name":"harverster0-bfab78a8","data-dir":"/var/lib/rancher/k3s/server/db/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/k3s/server/db/etcd/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["https://192.168.10.8:2380"],"advertise-client-urls":["https://192.168.10.8:2379"],"listen-client-urls":["https://127.0.0.1:2379","https://192.168.10.8:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":false,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":""}
panic: freepages: failed to get all reachable pages (page 8027998888435218021: out of bounds: 8557)
```

**Comment by yaocw2020** [comment]
I think it's the same problem with [ectd failed to get all reachable pages](https://github.com/etcd-io/etcd/issues/10722) @insbire
